/* eslint-disable */
import {
  CollectionCustomizer,
  TAggregation,
  TConditionTree,
  TPaginatedFilter,
  TPartialRow,
  TSortClause
} from '@forestadmin/agent';

export type DbApotheoseCustomizer = CollectionCustomizer<Schema, 'db_apotheose'>;
export type DbApotheoseRecord = TPartialRow<Schema, 'db_apotheose'>;
export type DbApotheoseConditionTree = TConditionTree<Schema, 'db_apotheose'>;
export type DbApotheoseFilter = TPaginatedFilter<Schema, 'db_apotheose'>;
export type DbApotheoseSortClause = TSortClause<Schema, 'db_apotheose'>;
export type DbApotheoseAggregation = TAggregation<Schema, 'db_apotheose'>;

export type DbBloodlineCustomizer = CollectionCustomizer<Schema, 'db_bloodline'>;
export type DbBloodlineRecord = TPartialRow<Schema, 'db_bloodline'>;
export type DbBloodlineConditionTree = TConditionTree<Schema, 'db_bloodline'>;
export type DbBloodlineFilter = TPaginatedFilter<Schema, 'db_bloodline'>;
export type DbBloodlineSortClause = TSortClause<Schema, 'db_bloodline'>;
export type DbBloodlineAggregation = TAggregation<Schema, 'db_bloodline'>;

export type DbBloodlineApotheoseCustomizer = CollectionCustomizer<Schema, 'db_bloodline_apotheose'>;
export type DbBloodlineApotheoseRecord = TPartialRow<Schema, 'db_bloodline_apotheose'>;
export type DbBloodlineApotheoseConditionTree = TConditionTree<Schema, 'db_bloodline_apotheose'>;
export type DbBloodlineApotheoseFilter = TPaginatedFilter<Schema, 'db_bloodline_apotheose'>;
export type DbBloodlineApotheoseSortClause = TSortClause<Schema, 'db_bloodline_apotheose'>;
export type DbBloodlineApotheoseAggregation = TAggregation<Schema, 'db_bloodline_apotheose'>;

export type DbBloodlineProficiencyCustomizer = CollectionCustomizer<Schema, 'db_bloodline_proficiency'>;
export type DbBloodlineProficiencyRecord = TPartialRow<Schema, 'db_bloodline_proficiency'>;
export type DbBloodlineProficiencyConditionTree = TConditionTree<Schema, 'db_bloodline_proficiency'>;
export type DbBloodlineProficiencyFilter = TPaginatedFilter<Schema, 'db_bloodline_proficiency'>;
export type DbBloodlineProficiencySortClause = TSortClause<Schema, 'db_bloodline_proficiency'>;
export type DbBloodlineProficiencyAggregation = TAggregation<Schema, 'db_bloodline_proficiency'>;

export type DbBloodlineSkillCustomizer = CollectionCustomizer<Schema, 'db_bloodline_skill'>;
export type DbBloodlineSkillRecord = TPartialRow<Schema, 'db_bloodline_skill'>;
export type DbBloodlineSkillConditionTree = TConditionTree<Schema, 'db_bloodline_skill'>;
export type DbBloodlineSkillFilter = TPaginatedFilter<Schema, 'db_bloodline_skill'>;
export type DbBloodlineSkillSortClause = TSortClause<Schema, 'db_bloodline_skill'>;
export type DbBloodlineSkillAggregation = TAggregation<Schema, 'db_bloodline_skill'>;

export type DbCharacterCustomizer = CollectionCustomizer<Schema, 'db_character'>;
export type DbCharacterRecord = TPartialRow<Schema, 'db_character'>;
export type DbCharacterConditionTree = TConditionTree<Schema, 'db_character'>;
export type DbCharacterFilter = TPaginatedFilter<Schema, 'db_character'>;
export type DbCharacterSortClause = TSortClause<Schema, 'db_character'>;
export type DbCharacterAggregation = TAggregation<Schema, 'db_character'>;

export type DbCharacterApotheoseCustomizer = CollectionCustomizer<Schema, 'db_character_apotheose'>;
export type DbCharacterApotheoseRecord = TPartialRow<Schema, 'db_character_apotheose'>;
export type DbCharacterApotheoseConditionTree = TConditionTree<Schema, 'db_character_apotheose'>;
export type DbCharacterApotheoseFilter = TPaginatedFilter<Schema, 'db_character_apotheose'>;
export type DbCharacterApotheoseSortClause = TSortClause<Schema, 'db_character_apotheose'>;
export type DbCharacterApotheoseAggregation = TAggregation<Schema, 'db_character_apotheose'>;

export type DbCharacterProficiencyCustomizer = CollectionCustomizer<Schema, 'db_character_proficiency'>;
export type DbCharacterProficiencyRecord = TPartialRow<Schema, 'db_character_proficiency'>;
export type DbCharacterProficiencyConditionTree = TConditionTree<Schema, 'db_character_proficiency'>;
export type DbCharacterProficiencyFilter = TPaginatedFilter<Schema, 'db_character_proficiency'>;
export type DbCharacterProficiencySortClause = TSortClause<Schema, 'db_character_proficiency'>;
export type DbCharacterProficiencyAggregation = TAggregation<Schema, 'db_character_proficiency'>;

export type DbCharacterSkillCustomizer = CollectionCustomizer<Schema, 'db_character_skill'>;
export type DbCharacterSkillRecord = TPartialRow<Schema, 'db_character_skill'>;
export type DbCharacterSkillConditionTree = TConditionTree<Schema, 'db_character_skill'>;
export type DbCharacterSkillFilter = TPaginatedFilter<Schema, 'db_character_skill'>;
export type DbCharacterSkillSortClause = TSortClause<Schema, 'db_character_skill'>;
export type DbCharacterSkillAggregation = TAggregation<Schema, 'db_character_skill'>;

export type DbCharacterTemplateCustomizer = CollectionCustomizer<Schema, 'db_character_template'>;
export type DbCharacterTemplateRecord = TPartialRow<Schema, 'db_character_template'>;
export type DbCharacterTemplateConditionTree = TConditionTree<Schema, 'db_character_template'>;
export type DbCharacterTemplateFilter = TPaginatedFilter<Schema, 'db_character_template'>;
export type DbCharacterTemplateSortClause = TSortClause<Schema, 'db_character_template'>;
export type DbCharacterTemplateAggregation = TAggregation<Schema, 'db_character_template'>;

export type DbCharacterTemplateSkillCustomizer = CollectionCustomizer<Schema, 'db_character_template_skill'>;
export type DbCharacterTemplateSkillRecord = TPartialRow<Schema, 'db_character_template_skill'>;
export type DbCharacterTemplateSkillConditionTree = TConditionTree<Schema, 'db_character_template_skill'>;
export type DbCharacterTemplateSkillFilter = TPaginatedFilter<Schema, 'db_character_template_skill'>;
export type DbCharacterTemplateSkillSortClause = TSortClause<Schema, 'db_character_template_skill'>;
export type DbCharacterTemplateSkillAggregation = TAggregation<Schema, 'db_character_template_skill'>;

export type DbClasseCustomizer = CollectionCustomizer<Schema, 'db_classe'>;
export type DbClasseRecord = TPartialRow<Schema, 'db_classe'>;
export type DbClasseConditionTree = TConditionTree<Schema, 'db_classe'>;
export type DbClasseFilter = TPaginatedFilter<Schema, 'db_classe'>;
export type DbClasseSortClause = TSortClause<Schema, 'db_classe'>;
export type DbClasseAggregation = TAggregation<Schema, 'db_classe'>;

export type DbClasseApotheoseCustomizer = CollectionCustomizer<Schema, 'db_classe_apotheose'>;
export type DbClasseApotheoseRecord = TPartialRow<Schema, 'db_classe_apotheose'>;
export type DbClasseApotheoseConditionTree = TConditionTree<Schema, 'db_classe_apotheose'>;
export type DbClasseApotheoseFilter = TPaginatedFilter<Schema, 'db_classe_apotheose'>;
export type DbClasseApotheoseSortClause = TSortClause<Schema, 'db_classe_apotheose'>;
export type DbClasseApotheoseAggregation = TAggregation<Schema, 'db_classe_apotheose'>;

export type DbClasseProficiencyCustomizer = CollectionCustomizer<Schema, 'db_classe_proficiency'>;
export type DbClasseProficiencyRecord = TPartialRow<Schema, 'db_classe_proficiency'>;
export type DbClasseProficiencyConditionTree = TConditionTree<Schema, 'db_classe_proficiency'>;
export type DbClasseProficiencyFilter = TPaginatedFilter<Schema, 'db_classe_proficiency'>;
export type DbClasseProficiencySortClause = TSortClause<Schema, 'db_classe_proficiency'>;
export type DbClasseProficiencyAggregation = TAggregation<Schema, 'db_classe_proficiency'>;

export type DbClasseSkillCustomizer = CollectionCustomizer<Schema, 'db_classe_skill'>;
export type DbClasseSkillRecord = TPartialRow<Schema, 'db_classe_skill'>;
export type DbClasseSkillConditionTree = TConditionTree<Schema, 'db_classe_skill'>;
export type DbClasseSkillFilter = TPaginatedFilter<Schema, 'db_classe_skill'>;
export type DbClasseSkillSortClause = TSortClause<Schema, 'db_classe_skill'>;
export type DbClasseSkillAggregation = TAggregation<Schema, 'db_classe_skill'>;

export type DbProficiencyCustomizer = CollectionCustomizer<Schema, 'db_proficiency'>;
export type DbProficiencyRecord = TPartialRow<Schema, 'db_proficiency'>;
export type DbProficiencyConditionTree = TConditionTree<Schema, 'db_proficiency'>;
export type DbProficiencyFilter = TPaginatedFilter<Schema, 'db_proficiency'>;
export type DbProficiencySortClause = TSortClause<Schema, 'db_proficiency'>;
export type DbProficiencyAggregation = TAggregation<Schema, 'db_proficiency'>;

export type DbRollCustomizer = CollectionCustomizer<Schema, 'db_roll'>;
export type DbRollRecord = TPartialRow<Schema, 'db_roll'>;
export type DbRollConditionTree = TConditionTree<Schema, 'db_roll'>;
export type DbRollFilter = TPaginatedFilter<Schema, 'db_roll'>;
export type DbRollSortClause = TSortClause<Schema, 'db_roll'>;
export type DbRollAggregation = TAggregation<Schema, 'db_roll'>;

export type DbSessionCustomizer = CollectionCustomizer<Schema, 'db_session'>;
export type DbSessionRecord = TPartialRow<Schema, 'db_session'>;
export type DbSessionConditionTree = TConditionTree<Schema, 'db_session'>;
export type DbSessionFilter = TPaginatedFilter<Schema, 'db_session'>;
export type DbSessionSortClause = TSortClause<Schema, 'db_session'>;
export type DbSessionAggregation = TAggregation<Schema, 'db_session'>;

export type DbSkillCustomizer = CollectionCustomizer<Schema, 'db_skill'>;
export type DbSkillRecord = TPartialRow<Schema, 'db_skill'>;
export type DbSkillConditionTree = TConditionTree<Schema, 'db_skill'>;
export type DbSkillFilter = TPaginatedFilter<Schema, 'db_skill'>;
export type DbSkillSortClause = TSortClause<Schema, 'db_skill'>;
export type DbSkillAggregation = TAggregation<Schema, 'db_skill'>;

export type DbTemplateCharacterSkillCustomizer = CollectionCustomizer<Schema, 'db_template_character_skill'>;
export type DbTemplateCharacterSkillRecord = TPartialRow<Schema, 'db_template_character_skill'>;
export type DbTemplateCharacterSkillConditionTree = TConditionTree<Schema, 'db_template_character_skill'>;
export type DbTemplateCharacterSkillFilter = TPaginatedFilter<Schema, 'db_template_character_skill'>;
export type DbTemplateCharacterSkillSortClause = TSortClause<Schema, 'db_template_character_skill'>;
export type DbTemplateCharacterSkillAggregation = TAggregation<Schema, 'db_template_character_skill'>;

export type MigrationsCustomizer = CollectionCustomizer<Schema, 'migrations'>;
export type MigrationsRecord = TPartialRow<Schema, 'migrations'>;
export type MigrationsConditionTree = TConditionTree<Schema, 'migrations'>;
export type MigrationsFilter = TPaginatedFilter<Schema, 'migrations'>;
export type MigrationsSortClause = TSortClause<Schema, 'migrations'>;
export type MigrationsAggregation = TAggregation<Schema, 'migrations'>;


export type Schema = {
  'db_apotheose': {
    plain: {
      'name': string;
      'shortName': string;
      'displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'MAGIE' | 'PACIFICATEURS' | 'SOLDATS' | 'STATS';
      'position': number;
      'minLevel': number;
      'maxLevel': number;
      'cost': number;
      'chairImprovement': number;
      'espritImprovement': number;
      'essenceImprovement': number;
      'arcaneImprovement': boolean;
      'avantage': boolean;
      'apotheoseEffect': string;
      'description': string;
    };
    nested: {};
    flat: {};
  };
  'db_bloodline': {
    plain: {
      'name': string;
      'display': string;
    };
    nested: {};
    flat: {};
  };
  'db_bloodline_apotheose': {
    plain: {
      'id': number;
      'bloodlineName': string;
      'apotheoseName': string;
    };
    nested: {
      'db_bloodline': Schema['db_bloodline']['plain'] & Schema['db_bloodline']['nested'];
      'db_apotheose': Schema['db_apotheose']['plain'] & Schema['db_apotheose']['nested'];
    };
    flat: {
      'db_bloodline:name': string;
      'db_bloodline:display': string;
      'db_apotheose:name': string;
      'db_apotheose:shortName': string;
      'db_apotheose:displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'MAGIE' | 'PACIFICATEURS' | 'SOLDATS' | 'STATS';
      'db_apotheose:position': number;
      'db_apotheose:minLevel': number;
      'db_apotheose:maxLevel': number;
      'db_apotheose:cost': number;
      'db_apotheose:chairImprovement': number;
      'db_apotheose:espritImprovement': number;
      'db_apotheose:essenceImprovement': number;
      'db_apotheose:arcaneImprovement': boolean;
      'db_apotheose:avantage': boolean;
      'db_apotheose:apotheoseEffect': string;
      'db_apotheose:description': string;
    };
  };
  'db_bloodline_proficiency': {
    plain: {
      'minLevel': number;
      'id': number;
      'bloodlineName': string;
      'proficiencyName': string;
    };
    nested: {
      'db_bloodline': Schema['db_bloodline']['plain'] & Schema['db_bloodline']['nested'];
      'db_proficiency': Schema['db_proficiency']['plain'] & Schema['db_proficiency']['nested'];
    };
    flat: {
      'db_bloodline:name': string;
      'db_bloodline:display': string;
      'db_proficiency:minLevel': number;
      'db_proficiency:name': string;
      'db_proficiency:shortName': string;
      'db_proficiency:displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'MAGIE' | 'PACIFICATEURS' | 'SOLDATS' | 'STATS';
      'db_proficiency:description': string;
    };
  };
  'db_bloodline_skill': {
    plain: {
      'allowsPf': boolean;
      'allowsPp': boolean;
      'stat': 'CHAIR' | 'CUSTOM' | 'EMPIRIQUE' | 'ESPRIT' | 'ESSENCE' | 'FIXE';
      'pvCost': number;
      'pfCost': number;
      'ppCost': number;
      'dettesCost': number;
      'arcaneCost': number;
      'customRolls': string;
      'successCalculation': 'AUCUN' | 'CUSTOM' | 'DIVISE' | 'DIVISE_PLUS_1' | 'DOUBLE' | 'DOUBLE_PLUS_1' | 'SIMPLE' | 'SIMPLE_PLUS_1';
      'secret': boolean;
      'invocationTemplateName': string;
      'id': number;
      'bloodlineName': string;
      'skillName': string;
      'displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'MAGIE' | 'PACIFICATEURS' | 'SOLDATS' | 'STATS';
      'arcanePrimeCost': number;
    };
    nested: {
      'db_character_template': Schema['db_character_template']['plain'] & Schema['db_character_template']['nested'];
      'db_bloodline': Schema['db_bloodline']['plain'] & Schema['db_bloodline']['nested'];
      'db_skill': Schema['db_skill']['plain'] & Schema['db_skill']['nested'];
    };
    flat: {
      'db_character_template:name': string;
      'db_character_template:chairValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:chairValueRule': number;
      'db_character_template:espritValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:espritValueRule': number;
      'db_character_template:essenceValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:essenceValueRule': number;
      'db_character_template:pvMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:pvMaxValueRule': number;
      'db_character_template:pfMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:pfMaxValueRule': number;
      'db_character_template:ppMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:ppMaxValueRule': number;
      'db_character_template:picture': string;
      'db_character_template:customData': string;
      'db_character_template:classeName': string;
      'db_character_template:bloodlineName': string;
      'db_character_template:db_classe:name': string;
      'db_character_template:db_classe:displayMale': string;
      'db_character_template:db_classe:displayFemale': string;
      'db_character_template:db_bloodline:name': string;
      'db_character_template:db_bloodline:display': string;
      'db_bloodline:name': string;
      'db_bloodline:display': string;
      'db_skill:allowsPf': boolean;
      'db_skill:allowsPp': boolean;
      'db_skill:stat': 'CHAIR' | 'CUSTOM' | 'EMPIRIQUE' | 'ESPRIT' | 'ESSENCE' | 'FIXE';
      'db_skill:pvCost': number;
      'db_skill:pfCost': number;
      'db_skill:ppCost': number;
      'db_skill:dettesCost': number;
      'db_skill:arcaneCost': number;
      'db_skill:customRolls': string;
      'db_skill:successCalculation': 'AUCUN' | 'CUSTOM' | 'DIVISE' | 'DIVISE_PLUS_1' | 'DOUBLE' | 'DOUBLE_PLUS_1' | 'SIMPLE' | 'SIMPLE_PLUS_1';
      'db_skill:secret': boolean;
      'db_skill:invocationTemplateName': string;
      'db_skill:name': string;
      'db_skill:shortName': string;
      'db_skill:allAttribution': boolean;
      'db_skill:displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'MAGIE' | 'PACIFICATEURS' | 'SOLDATS' | 'STATS';
      'db_skill:position': number;
      'db_skill:display': string;
      'db_skill:isArcanique': boolean;
      'db_skill:description': string;
      'db_skill:longName': string;
      'db_skill:arcanePrimeCost': number;
      'db_skill:precision': string;
      'db_skill:soldatCost': number;
      'db_skill:db_character_template:name': string;
      'db_skill:db_character_template:chairValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:chairValueRule': number;
      'db_skill:db_character_template:espritValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:espritValueRule': number;
      'db_skill:db_character_template:essenceValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:essenceValueRule': number;
      'db_skill:db_character_template:pvMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:pvMaxValueRule': number;
      'db_skill:db_character_template:pfMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:pfMaxValueRule': number;
      'db_skill:db_character_template:ppMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:ppMaxValueRule': number;
      'db_skill:db_character_template:picture': string;
      'db_skill:db_character_template:customData': string;
      'db_skill:db_character_template:classeName': string;
      'db_skill:db_character_template:bloodlineName': string;
      'db_skill:db_character_template:db_classe:name': string;
      'db_skill:db_character_template:db_classe:displayMale': string;
      'db_skill:db_character_template:db_classe:displayFemale': string;
      'db_skill:db_character_template:db_bloodline:name': string;
      'db_skill:db_character_template:db_bloodline:display': string;
    };
  };
  'db_character': {
    plain: {
      'name': string;
      'classeName': string;
      'controlledBy': string;
      'isInvocation': boolean;
      'apotheoseName': string;
      'apotheoseState': 'ALREADY_USED' | 'COST_PAID' | 'COST_TO_PAY' | 'NONE';
      'apotheoseImprovement': string;
      'apotheoseImprovementList': string;
      'chair': number;
      'esprit': number;
      'essence': number;
      'pv': number;
      'pvMax': number;
      'pf': number;
      'pfMax': number;
      'pp': number;
      'ppMax': number;
      'dettes': number;
      'arcanes': number;
      'arcanesMax': number;
      'niveau': number;
      'restImproved': boolean;
      'lux': string;
      'umbra': string;
      'secunda': string;
      'notes': string;
      'battleState': 'ALLIES' | 'ENNEMIES' | 'NONE';
      'genre': 'FEMME' | 'HOMME';
      'relance': number;
      'playerName': string;
      'picture': string;
      'pictureApotheose': string;
      'background': string;
      'buttonColor': string;
      'textColor': string;
      'boosted': boolean;
      'bloodlineName': string;
      'arcanePrimes': number;
      'arcanePrimesMax': number;
      'munitions': number;
      'munitionsMax': number;
      'customData': string;
    };
    nested: {
      'db_classe': Schema['db_classe']['plain'] & Schema['db_classe']['nested'];
      'db_bloodline': Schema['db_bloodline']['plain'] & Schema['db_bloodline']['nested'];
    };
    flat: {
      'db_classe:name': string;
      'db_classe:displayMale': string;
      'db_classe:displayFemale': string;
      'db_bloodline:name': string;
      'db_bloodline:display': string;
    };
  };
  'db_character_apotheose': {
    plain: {
      'id': number;
      'characterName': string;
      'apotheoseName': string;
    };
    nested: {
      'db_character': Schema['db_character']['plain'] & Schema['db_character']['nested'];
      'db_apotheose': Schema['db_apotheose']['plain'] & Schema['db_apotheose']['nested'];
    };
    flat: {
      'db_character:name': string;
      'db_character:classeName': string;
      'db_character:controlledBy': string;
      'db_character:isInvocation': boolean;
      'db_character:apotheoseName': string;
      'db_character:apotheoseState': 'ALREADY_USED' | 'COST_PAID' | 'COST_TO_PAY' | 'NONE';
      'db_character:apotheoseImprovement': string;
      'db_character:apotheoseImprovementList': string;
      'db_character:chair': number;
      'db_character:esprit': number;
      'db_character:essence': number;
      'db_character:pv': number;
      'db_character:pvMax': number;
      'db_character:pf': number;
      'db_character:pfMax': number;
      'db_character:pp': number;
      'db_character:ppMax': number;
      'db_character:dettes': number;
      'db_character:arcanes': number;
      'db_character:arcanesMax': number;
      'db_character:niveau': number;
      'db_character:restImproved': boolean;
      'db_character:lux': string;
      'db_character:umbra': string;
      'db_character:secunda': string;
      'db_character:notes': string;
      'db_character:battleState': 'ALLIES' | 'ENNEMIES' | 'NONE';
      'db_character:genre': 'FEMME' | 'HOMME';
      'db_character:relance': number;
      'db_character:playerName': string;
      'db_character:picture': string;
      'db_character:pictureApotheose': string;
      'db_character:background': string;
      'db_character:buttonColor': string;
      'db_character:textColor': string;
      'db_character:boosted': boolean;
      'db_character:bloodlineName': string;
      'db_character:arcanePrimes': number;
      'db_character:arcanePrimesMax': number;
      'db_character:munitions': number;
      'db_character:munitionsMax': number;
      'db_character:customData': string;
      'db_character:db_classe:name': string;
      'db_character:db_classe:displayMale': string;
      'db_character:db_classe:displayFemale': string;
      'db_character:db_bloodline:name': string;
      'db_character:db_bloodline:display': string;
      'db_apotheose:name': string;
      'db_apotheose:shortName': string;
      'db_apotheose:displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'MAGIE' | 'PACIFICATEURS' | 'SOLDATS' | 'STATS';
      'db_apotheose:position': number;
      'db_apotheose:minLevel': number;
      'db_apotheose:maxLevel': number;
      'db_apotheose:cost': number;
      'db_apotheose:chairImprovement': number;
      'db_apotheose:espritImprovement': number;
      'db_apotheose:essenceImprovement': number;
      'db_apotheose:arcaneImprovement': boolean;
      'db_apotheose:avantage': boolean;
      'db_apotheose:apotheoseEffect': string;
      'db_apotheose:description': string;
    };
  };
  'db_character_proficiency': {
    plain: {
      'minLevel': number;
      'id': number;
      'characterName': string;
      'proficiencyName': string;
    };
    nested: {
      'db_character': Schema['db_character']['plain'] & Schema['db_character']['nested'];
      'db_proficiency': Schema['db_proficiency']['plain'] & Schema['db_proficiency']['nested'];
    };
    flat: {
      'db_character:name': string;
      'db_character:classeName': string;
      'db_character:controlledBy': string;
      'db_character:isInvocation': boolean;
      'db_character:apotheoseName': string;
      'db_character:apotheoseState': 'ALREADY_USED' | 'COST_PAID' | 'COST_TO_PAY' | 'NONE';
      'db_character:apotheoseImprovement': string;
      'db_character:apotheoseImprovementList': string;
      'db_character:chair': number;
      'db_character:esprit': number;
      'db_character:essence': number;
      'db_character:pv': number;
      'db_character:pvMax': number;
      'db_character:pf': number;
      'db_character:pfMax': number;
      'db_character:pp': number;
      'db_character:ppMax': number;
      'db_character:dettes': number;
      'db_character:arcanes': number;
      'db_character:arcanesMax': number;
      'db_character:niveau': number;
      'db_character:restImproved': boolean;
      'db_character:lux': string;
      'db_character:umbra': string;
      'db_character:secunda': string;
      'db_character:notes': string;
      'db_character:battleState': 'ALLIES' | 'ENNEMIES' | 'NONE';
      'db_character:genre': 'FEMME' | 'HOMME';
      'db_character:relance': number;
      'db_character:playerName': string;
      'db_character:picture': string;
      'db_character:pictureApotheose': string;
      'db_character:background': string;
      'db_character:buttonColor': string;
      'db_character:textColor': string;
      'db_character:boosted': boolean;
      'db_character:bloodlineName': string;
      'db_character:arcanePrimes': number;
      'db_character:arcanePrimesMax': number;
      'db_character:munitions': number;
      'db_character:munitionsMax': number;
      'db_character:customData': string;
      'db_character:db_classe:name': string;
      'db_character:db_classe:displayMale': string;
      'db_character:db_classe:displayFemale': string;
      'db_character:db_bloodline:name': string;
      'db_character:db_bloodline:display': string;
      'db_proficiency:minLevel': number;
      'db_proficiency:name': string;
      'db_proficiency:shortName': string;
      'db_proficiency:displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'MAGIE' | 'PACIFICATEURS' | 'SOLDATS' | 'STATS';
      'db_proficiency:description': string;
    };
  };
  'db_character_skill': {
    plain: {
      'allowsPf': boolean;
      'allowsPp': boolean;
      'stat': 'CHAIR' | 'CUSTOM' | 'EMPIRIQUE' | 'ESPRIT' | 'ESSENCE' | 'FIXE';
      'pvCost': number;
      'pfCost': number;
      'ppCost': number;
      'dettesCost': number;
      'arcaneCost': number;
      'customRolls': string;
      'successCalculation': 'AUCUN' | 'CUSTOM' | 'DIVISE' | 'DIVISE_PLUS_1' | 'DOUBLE' | 'DOUBLE_PLUS_1' | 'SIMPLE' | 'SIMPLE_PLUS_1';
      'secret': boolean;
      'invocationTemplateName': string;
      'id': number;
      'characterName': string;
      'skillName': string;
      'dailyUse': number;
      'limitationMax': number;
      'displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'MAGIE' | 'PACIFICATEURS' | 'SOLDATS' | 'STATS';
      'arcanePrimeCost': number;
    };
    nested: {
      'db_character_template': Schema['db_character_template']['plain'] & Schema['db_character_template']['nested'];
      'db_character': Schema['db_character']['plain'] & Schema['db_character']['nested'];
      'db_skill': Schema['db_skill']['plain'] & Schema['db_skill']['nested'];
    };
    flat: {
      'db_character_template:name': string;
      'db_character_template:chairValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:chairValueRule': number;
      'db_character_template:espritValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:espritValueRule': number;
      'db_character_template:essenceValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:essenceValueRule': number;
      'db_character_template:pvMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:pvMaxValueRule': number;
      'db_character_template:pfMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:pfMaxValueRule': number;
      'db_character_template:ppMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:ppMaxValueRule': number;
      'db_character_template:picture': string;
      'db_character_template:customData': string;
      'db_character_template:classeName': string;
      'db_character_template:bloodlineName': string;
      'db_character_template:db_classe:name': string;
      'db_character_template:db_classe:displayMale': string;
      'db_character_template:db_classe:displayFemale': string;
      'db_character_template:db_bloodline:name': string;
      'db_character_template:db_bloodline:display': string;
      'db_character:name': string;
      'db_character:classeName': string;
      'db_character:controlledBy': string;
      'db_character:isInvocation': boolean;
      'db_character:apotheoseName': string;
      'db_character:apotheoseState': 'ALREADY_USED' | 'COST_PAID' | 'COST_TO_PAY' | 'NONE';
      'db_character:apotheoseImprovement': string;
      'db_character:apotheoseImprovementList': string;
      'db_character:chair': number;
      'db_character:esprit': number;
      'db_character:essence': number;
      'db_character:pv': number;
      'db_character:pvMax': number;
      'db_character:pf': number;
      'db_character:pfMax': number;
      'db_character:pp': number;
      'db_character:ppMax': number;
      'db_character:dettes': number;
      'db_character:arcanes': number;
      'db_character:arcanesMax': number;
      'db_character:niveau': number;
      'db_character:restImproved': boolean;
      'db_character:lux': string;
      'db_character:umbra': string;
      'db_character:secunda': string;
      'db_character:notes': string;
      'db_character:battleState': 'ALLIES' | 'ENNEMIES' | 'NONE';
      'db_character:genre': 'FEMME' | 'HOMME';
      'db_character:relance': number;
      'db_character:playerName': string;
      'db_character:picture': string;
      'db_character:pictureApotheose': string;
      'db_character:background': string;
      'db_character:buttonColor': string;
      'db_character:textColor': string;
      'db_character:boosted': boolean;
      'db_character:bloodlineName': string;
      'db_character:arcanePrimes': number;
      'db_character:arcanePrimesMax': number;
      'db_character:munitions': number;
      'db_character:munitionsMax': number;
      'db_character:customData': string;
      'db_character:db_classe:name': string;
      'db_character:db_classe:displayMale': string;
      'db_character:db_classe:displayFemale': string;
      'db_character:db_bloodline:name': string;
      'db_character:db_bloodline:display': string;
      'db_skill:allowsPf': boolean;
      'db_skill:allowsPp': boolean;
      'db_skill:stat': 'CHAIR' | 'CUSTOM' | 'EMPIRIQUE' | 'ESPRIT' | 'ESSENCE' | 'FIXE';
      'db_skill:pvCost': number;
      'db_skill:pfCost': number;
      'db_skill:ppCost': number;
      'db_skill:dettesCost': number;
      'db_skill:arcaneCost': number;
      'db_skill:customRolls': string;
      'db_skill:successCalculation': 'AUCUN' | 'CUSTOM' | 'DIVISE' | 'DIVISE_PLUS_1' | 'DOUBLE' | 'DOUBLE_PLUS_1' | 'SIMPLE' | 'SIMPLE_PLUS_1';
      'db_skill:secret': boolean;
      'db_skill:invocationTemplateName': string;
      'db_skill:name': string;
      'db_skill:shortName': string;
      'db_skill:allAttribution': boolean;
      'db_skill:displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'MAGIE' | 'PACIFICATEURS' | 'SOLDATS' | 'STATS';
      'db_skill:position': number;
      'db_skill:display': string;
      'db_skill:isArcanique': boolean;
      'db_skill:description': string;
      'db_skill:longName': string;
      'db_skill:arcanePrimeCost': number;
      'db_skill:precision': string;
      'db_skill:soldatCost': number;
      'db_skill:db_character_template:name': string;
      'db_skill:db_character_template:chairValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:chairValueRule': number;
      'db_skill:db_character_template:espritValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:espritValueRule': number;
      'db_skill:db_character_template:essenceValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:essenceValueRule': number;
      'db_skill:db_character_template:pvMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:pvMaxValueRule': number;
      'db_skill:db_character_template:pfMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:pfMaxValueRule': number;
      'db_skill:db_character_template:ppMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:ppMaxValueRule': number;
      'db_skill:db_character_template:picture': string;
      'db_skill:db_character_template:customData': string;
      'db_skill:db_character_template:classeName': string;
      'db_skill:db_character_template:bloodlineName': string;
      'db_skill:db_character_template:db_classe:name': string;
      'db_skill:db_character_template:db_classe:displayMale': string;
      'db_skill:db_character_template:db_classe:displayFemale': string;
      'db_skill:db_character_template:db_bloodline:name': string;
      'db_skill:db_character_template:db_bloodline:display': string;
    };
  };
  'db_character_template': {
    plain: {
      'name': string;
      'chairValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'chairValueRule': number;
      'espritValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'espritValueRule': number;
      'essenceValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'essenceValueRule': number;
      'pvMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'pvMaxValueRule': number;
      'pfMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'pfMaxValueRule': number;
      'ppMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'ppMaxValueRule': number;
      'picture': string;
      'customData': string;
      'classeName': string;
      'bloodlineName': string;
    };
    nested: {
      'db_classe': Schema['db_classe']['plain'] & Schema['db_classe']['nested'];
      'db_bloodline': Schema['db_bloodline']['plain'] & Schema['db_bloodline']['nested'];
    };
    flat: {
      'db_classe:name': string;
      'db_classe:displayMale': string;
      'db_classe:displayFemale': string;
      'db_bloodline:name': string;
      'db_bloodline:display': string;
    };
  };
  'db_character_template_skill': {
    plain: {
      'displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'MAGIE' | 'PACIFICATEURS' | 'SOLDATS' | 'STATS';
      'allowsPf': boolean;
      'allowsPp': boolean;
      'stat': 'CHAIR' | 'CUSTOM' | 'EMPIRIQUE' | 'ESPRIT' | 'ESSENCE' | 'FIXE';
      'pvCost': number;
      'pfCost': number;
      'ppCost': number;
      'dettesCost': number;
      'arcaneCost': number;
      'arcanePrimeCost': number;
      'customRolls': string;
      'successCalculation': 'AUCUN' | 'CUSTOM' | 'DIVISE' | 'DIVISE_PLUS_1' | 'DOUBLE' | 'DOUBLE_PLUS_1' | 'SIMPLE' | 'SIMPLE_PLUS_1';
      'secret': boolean;
      'invocationTemplateName': string;
      'id': number;
      'characterTemplateName': string;
      'skillName': string;
      'dailyUse': number;
      'limitationMax': number;
    };
    nested: {
      'db_character_template_through_invocationTemplateName': Schema['db_character_template']['plain'] & Schema['db_character_template']['nested'];
      'db_character_template_through_characterTemplateName': Schema['db_character_template']['plain'] & Schema['db_character_template']['nested'];
      'db_skill': Schema['db_skill']['plain'] & Schema['db_skill']['nested'];
    };
    flat: {
      'db_character_template_through_invocationTemplateName:name': string;
      'db_character_template_through_invocationTemplateName:chairValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template_through_invocationTemplateName:chairValueRule': number;
      'db_character_template_through_invocationTemplateName:espritValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template_through_invocationTemplateName:espritValueRule': number;
      'db_character_template_through_invocationTemplateName:essenceValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template_through_invocationTemplateName:essenceValueRule': number;
      'db_character_template_through_invocationTemplateName:pvMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template_through_invocationTemplateName:pvMaxValueRule': number;
      'db_character_template_through_invocationTemplateName:pfMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template_through_invocationTemplateName:pfMaxValueRule': number;
      'db_character_template_through_invocationTemplateName:ppMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template_through_invocationTemplateName:ppMaxValueRule': number;
      'db_character_template_through_invocationTemplateName:picture': string;
      'db_character_template_through_invocationTemplateName:customData': string;
      'db_character_template_through_invocationTemplateName:classeName': string;
      'db_character_template_through_invocationTemplateName:bloodlineName': string;
      'db_character_template_through_invocationTemplateName:db_classe:name': string;
      'db_character_template_through_invocationTemplateName:db_classe:displayMale': string;
      'db_character_template_through_invocationTemplateName:db_classe:displayFemale': string;
      'db_character_template_through_invocationTemplateName:db_bloodline:name': string;
      'db_character_template_through_invocationTemplateName:db_bloodline:display': string;
      'db_character_template_through_characterTemplateName:name': string;
      'db_character_template_through_characterTemplateName:chairValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template_through_characterTemplateName:chairValueRule': number;
      'db_character_template_through_characterTemplateName:espritValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template_through_characterTemplateName:espritValueRule': number;
      'db_character_template_through_characterTemplateName:essenceValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template_through_characterTemplateName:essenceValueRule': number;
      'db_character_template_through_characterTemplateName:pvMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template_through_characterTemplateName:pvMaxValueRule': number;
      'db_character_template_through_characterTemplateName:pfMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template_through_characterTemplateName:pfMaxValueRule': number;
      'db_character_template_through_characterTemplateName:ppMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template_through_characterTemplateName:ppMaxValueRule': number;
      'db_character_template_through_characterTemplateName:picture': string;
      'db_character_template_through_characterTemplateName:customData': string;
      'db_character_template_through_characterTemplateName:classeName': string;
      'db_character_template_through_characterTemplateName:bloodlineName': string;
      'db_character_template_through_characterTemplateName:db_classe:name': string;
      'db_character_template_through_characterTemplateName:db_classe:displayMale': string;
      'db_character_template_through_characterTemplateName:db_classe:displayFemale': string;
      'db_character_template_through_characterTemplateName:db_bloodline:name': string;
      'db_character_template_through_characterTemplateName:db_bloodline:display': string;
      'db_skill:allowsPf': boolean;
      'db_skill:allowsPp': boolean;
      'db_skill:stat': 'CHAIR' | 'CUSTOM' | 'EMPIRIQUE' | 'ESPRIT' | 'ESSENCE' | 'FIXE';
      'db_skill:pvCost': number;
      'db_skill:pfCost': number;
      'db_skill:ppCost': number;
      'db_skill:dettesCost': number;
      'db_skill:arcaneCost': number;
      'db_skill:customRolls': string;
      'db_skill:successCalculation': 'AUCUN' | 'CUSTOM' | 'DIVISE' | 'DIVISE_PLUS_1' | 'DOUBLE' | 'DOUBLE_PLUS_1' | 'SIMPLE' | 'SIMPLE_PLUS_1';
      'db_skill:secret': boolean;
      'db_skill:invocationTemplateName': string;
      'db_skill:name': string;
      'db_skill:shortName': string;
      'db_skill:allAttribution': boolean;
      'db_skill:displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'MAGIE' | 'PACIFICATEURS' | 'SOLDATS' | 'STATS';
      'db_skill:position': number;
      'db_skill:display': string;
      'db_skill:isArcanique': boolean;
      'db_skill:description': string;
      'db_skill:longName': string;
      'db_skill:arcanePrimeCost': number;
      'db_skill:precision': string;
      'db_skill:soldatCost': number;
      'db_skill:db_character_template:name': string;
      'db_skill:db_character_template:chairValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:chairValueRule': number;
      'db_skill:db_character_template:espritValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:espritValueRule': number;
      'db_skill:db_character_template:essenceValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:essenceValueRule': number;
      'db_skill:db_character_template:pvMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:pvMaxValueRule': number;
      'db_skill:db_character_template:pfMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:pfMaxValueRule': number;
      'db_skill:db_character_template:ppMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:ppMaxValueRule': number;
      'db_skill:db_character_template:picture': string;
      'db_skill:db_character_template:customData': string;
      'db_skill:db_character_template:classeName': string;
      'db_skill:db_character_template:bloodlineName': string;
      'db_skill:db_character_template:db_classe:name': string;
      'db_skill:db_character_template:db_classe:displayMale': string;
      'db_skill:db_character_template:db_classe:displayFemale': string;
      'db_skill:db_character_template:db_bloodline:name': string;
      'db_skill:db_character_template:db_bloodline:display': string;
    };
  };
  'db_classe': {
    plain: {
      'name': string;
      'displayMale': string;
      'displayFemale': string;
    };
    nested: {};
    flat: {};
  };
  'db_classe_apotheose': {
    plain: {
      'id': number;
      'classeName': string;
      'apotheoseName': string;
    };
    nested: {
      'db_classe': Schema['db_classe']['plain'] & Schema['db_classe']['nested'];
      'db_apotheose': Schema['db_apotheose']['plain'] & Schema['db_apotheose']['nested'];
    };
    flat: {
      'db_classe:name': string;
      'db_classe:displayMale': string;
      'db_classe:displayFemale': string;
      'db_apotheose:name': string;
      'db_apotheose:shortName': string;
      'db_apotheose:displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'MAGIE' | 'PACIFICATEURS' | 'SOLDATS' | 'STATS';
      'db_apotheose:position': number;
      'db_apotheose:minLevel': number;
      'db_apotheose:maxLevel': number;
      'db_apotheose:cost': number;
      'db_apotheose:chairImprovement': number;
      'db_apotheose:espritImprovement': number;
      'db_apotheose:essenceImprovement': number;
      'db_apotheose:arcaneImprovement': boolean;
      'db_apotheose:avantage': boolean;
      'db_apotheose:apotheoseEffect': string;
      'db_apotheose:description': string;
    };
  };
  'db_classe_proficiency': {
    plain: {
      'minLevel': number;
      'id': number;
      'classeName': string;
      'proficiencyName': string;
    };
    nested: {
      'db_classe': Schema['db_classe']['plain'] & Schema['db_classe']['nested'];
      'db_proficiency': Schema['db_proficiency']['plain'] & Schema['db_proficiency']['nested'];
    };
    flat: {
      'db_classe:name': string;
      'db_classe:displayMale': string;
      'db_classe:displayFemale': string;
      'db_proficiency:minLevel': number;
      'db_proficiency:name': string;
      'db_proficiency:shortName': string;
      'db_proficiency:displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'MAGIE' | 'PACIFICATEURS' | 'SOLDATS' | 'STATS';
      'db_proficiency:description': string;
    };
  };
  'db_classe_skill': {
    plain: {
      'allowsPf': boolean;
      'allowsPp': boolean;
      'stat': 'CHAIR' | 'CUSTOM' | 'EMPIRIQUE' | 'ESPRIT' | 'ESSENCE' | 'FIXE';
      'pvCost': number;
      'pfCost': number;
      'ppCost': number;
      'dettesCost': number;
      'arcaneCost': number;
      'customRolls': string;
      'successCalculation': 'AUCUN' | 'CUSTOM' | 'DIVISE' | 'DIVISE_PLUS_1' | 'DOUBLE' | 'DOUBLE_PLUS_1' | 'SIMPLE' | 'SIMPLE_PLUS_1';
      'secret': boolean;
      'invocationTemplateName': string;
      'id': number;
      'classeName': string;
      'skillName': string;
      'displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'MAGIE' | 'PACIFICATEURS' | 'SOLDATS' | 'STATS';
      'arcanePrimeCost': number;
    };
    nested: {
      'db_character_template': Schema['db_character_template']['plain'] & Schema['db_character_template']['nested'];
      'db_classe': Schema['db_classe']['plain'] & Schema['db_classe']['nested'];
      'db_skill': Schema['db_skill']['plain'] & Schema['db_skill']['nested'];
    };
    flat: {
      'db_character_template:name': string;
      'db_character_template:chairValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:chairValueRule': number;
      'db_character_template:espritValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:espritValueRule': number;
      'db_character_template:essenceValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:essenceValueRule': number;
      'db_character_template:pvMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:pvMaxValueRule': number;
      'db_character_template:pfMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:pfMaxValueRule': number;
      'db_character_template:ppMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:ppMaxValueRule': number;
      'db_character_template:picture': string;
      'db_character_template:customData': string;
      'db_character_template:classeName': string;
      'db_character_template:bloodlineName': string;
      'db_character_template:db_classe:name': string;
      'db_character_template:db_classe:displayMale': string;
      'db_character_template:db_classe:displayFemale': string;
      'db_character_template:db_bloodline:name': string;
      'db_character_template:db_bloodline:display': string;
      'db_classe:name': string;
      'db_classe:displayMale': string;
      'db_classe:displayFemale': string;
      'db_skill:allowsPf': boolean;
      'db_skill:allowsPp': boolean;
      'db_skill:stat': 'CHAIR' | 'CUSTOM' | 'EMPIRIQUE' | 'ESPRIT' | 'ESSENCE' | 'FIXE';
      'db_skill:pvCost': number;
      'db_skill:pfCost': number;
      'db_skill:ppCost': number;
      'db_skill:dettesCost': number;
      'db_skill:arcaneCost': number;
      'db_skill:customRolls': string;
      'db_skill:successCalculation': 'AUCUN' | 'CUSTOM' | 'DIVISE' | 'DIVISE_PLUS_1' | 'DOUBLE' | 'DOUBLE_PLUS_1' | 'SIMPLE' | 'SIMPLE_PLUS_1';
      'db_skill:secret': boolean;
      'db_skill:invocationTemplateName': string;
      'db_skill:name': string;
      'db_skill:shortName': string;
      'db_skill:allAttribution': boolean;
      'db_skill:displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'MAGIE' | 'PACIFICATEURS' | 'SOLDATS' | 'STATS';
      'db_skill:position': number;
      'db_skill:display': string;
      'db_skill:isArcanique': boolean;
      'db_skill:description': string;
      'db_skill:longName': string;
      'db_skill:arcanePrimeCost': number;
      'db_skill:precision': string;
      'db_skill:soldatCost': number;
      'db_skill:db_character_template:name': string;
      'db_skill:db_character_template:chairValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:chairValueRule': number;
      'db_skill:db_character_template:espritValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:espritValueRule': number;
      'db_skill:db_character_template:essenceValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:essenceValueRule': number;
      'db_skill:db_character_template:pvMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:pvMaxValueRule': number;
      'db_skill:db_character_template:pfMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:pfMaxValueRule': number;
      'db_skill:db_character_template:ppMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:ppMaxValueRule': number;
      'db_skill:db_character_template:picture': string;
      'db_skill:db_character_template:customData': string;
      'db_skill:db_character_template:classeName': string;
      'db_skill:db_character_template:bloodlineName': string;
      'db_skill:db_character_template:db_classe:name': string;
      'db_skill:db_character_template:db_classe:displayMale': string;
      'db_skill:db_character_template:db_classe:displayFemale': string;
      'db_skill:db_character_template:db_bloodline:name': string;
      'db_skill:db_character_template:db_bloodline:display': string;
    };
  };
  'db_proficiency': {
    plain: {
      'minLevel': number;
      'name': string;
      'shortName': string;
      'displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'MAGIE' | 'PACIFICATEURS' | 'SOLDATS' | 'STATS';
      'description': string;
    };
    nested: {};
    flat: {};
  };
  'db_roll': {
    plain: {
      'id': number;
      'rollerName': string;
      'date': string;
      'stat': 'CHAIR' | 'CUSTOM' | 'EMPIRIQUE' | 'ESPRIT' | 'ESSENCE' | 'FIXE';
      'secret': boolean;
      'displayDices': boolean;
      'focus': boolean;
      'power': boolean;
      'proficiency': boolean;
      'bonus': number;
      'malus': number;
      'result': string;
      'success': number;
      'juge12': number;
      'juge34': number;
      'picture': string;
      'data': string;
      'empiriqueRoll': string;
      'resistRoll': string;
      'display': string;
    };
    nested: {};
    flat: {};
  };
  'db_session': {
    plain: {
      'id': number;
      'chaos': '0' | '15' | '30' | '45' | '60' | '75';
      'baseRest': number;
      'improvedRest': number;
      'nature': 'LEVEL_0_PAUVRE' | 'LEVEL_1_RARE' | 'LEVEL_2_PRESENTE' | 'LEVEL_3_ABONDANTE' | 'LEVEL_4_RICHE' | 'LEVEL_5_DOMINANTE';
    };
    nested: {};
    flat: {};
  };
  'db_skill': {
    plain: {
      'allowsPf': boolean;
      'allowsPp': boolean;
      'stat': 'CHAIR' | 'CUSTOM' | 'EMPIRIQUE' | 'ESPRIT' | 'ESSENCE' | 'FIXE';
      'pvCost': number;
      'pfCost': number;
      'ppCost': number;
      'dettesCost': number;
      'arcaneCost': number;
      'customRolls': string;
      'successCalculation': 'AUCUN' | 'CUSTOM' | 'DIVISE' | 'DIVISE_PLUS_1' | 'DOUBLE' | 'DOUBLE_PLUS_1' | 'SIMPLE' | 'SIMPLE_PLUS_1';
      'secret': boolean;
      'invocationTemplateName': string;
      'name': string;
      'shortName': string;
      'allAttribution': boolean;
      'displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'MAGIE' | 'PACIFICATEURS' | 'SOLDATS' | 'STATS';
      'position': number;
      'display': string;
      'isArcanique': boolean;
      'description': string;
      'longName': string;
      'arcanePrimeCost': number;
      'precision': string;
      'soldatCost': number;
    };
    nested: {
      'db_character_template': Schema['db_character_template']['plain'] & Schema['db_character_template']['nested'];
    };
    flat: {
      'db_character_template:name': string;
      'db_character_template:chairValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:chairValueRule': number;
      'db_character_template:espritValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:espritValueRule': number;
      'db_character_template:essenceValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:essenceValueRule': number;
      'db_character_template:pvMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:pvMaxValueRule': number;
      'db_character_template:pfMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:pfMaxValueRule': number;
      'db_character_template:ppMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:ppMaxValueRule': number;
      'db_character_template:picture': string;
      'db_character_template:customData': string;
      'db_character_template:classeName': string;
      'db_character_template:bloodlineName': string;
      'db_character_template:db_classe:name': string;
      'db_character_template:db_classe:displayMale': string;
      'db_character_template:db_classe:displayFemale': string;
      'db_character_template:db_bloodline:name': string;
      'db_character_template:db_bloodline:display': string;
    };
  };
  'db_template_character_skill': {
    plain: {
      'displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'MAGIE' | 'PACIFICATEURS' | 'SOLDATS' | 'STATS';
      'allowsPf': boolean;
      'allowsPp': boolean;
      'stat': 'CHAIR' | 'CUSTOM' | 'EMPIRIQUE' | 'ESPRIT' | 'ESSENCE' | 'FIXE';
      'pvCost': number;
      'pfCost': number;
      'ppCost': number;
      'dettesCost': number;
      'arcaneCost': number;
      'arcanePrimeCost': number;
      'customRolls': string;
      'successCalculation': 'AUCUN' | 'CUSTOM' | 'DIVISE' | 'DIVISE_PLUS_1' | 'SIMPLE' | 'SIMPLE_PLUS_1';
      'secret': boolean;
      'invocationTemplateName': string;
      'id': number;
      'templateCharacterName': string;
      'skillName': string;
    };
    nested: {
      'db_character_template_through_invocationTemplateName': Schema['db_character_template']['plain'] & Schema['db_character_template']['nested'];
      'db_character_template_through_templateCharacterName': Schema['db_character_template']['plain'] & Schema['db_character_template']['nested'];
      'db_skill': Schema['db_skill']['plain'] & Schema['db_skill']['nested'];
    };
    flat: {
      'db_character_template_through_invocationTemplateName:name': string;
      'db_character_template_through_invocationTemplateName:chairValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template_through_invocationTemplateName:chairValueRule': number;
      'db_character_template_through_invocationTemplateName:espritValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template_through_invocationTemplateName:espritValueRule': number;
      'db_character_template_through_invocationTemplateName:essenceValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template_through_invocationTemplateName:essenceValueRule': number;
      'db_character_template_through_invocationTemplateName:pvMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template_through_invocationTemplateName:pvMaxValueRule': number;
      'db_character_template_through_invocationTemplateName:pfMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template_through_invocationTemplateName:pfMaxValueRule': number;
      'db_character_template_through_invocationTemplateName:ppMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template_through_invocationTemplateName:ppMaxValueRule': number;
      'db_character_template_through_invocationTemplateName:picture': string;
      'db_character_template_through_invocationTemplateName:customData': string;
      'db_character_template_through_invocationTemplateName:classeName': string;
      'db_character_template_through_invocationTemplateName:bloodlineName': string;
      'db_character_template_through_invocationTemplateName:db_classe:name': string;
      'db_character_template_through_invocationTemplateName:db_classe:displayMale': string;
      'db_character_template_through_invocationTemplateName:db_classe:displayFemale': string;
      'db_character_template_through_invocationTemplateName:db_bloodline:name': string;
      'db_character_template_through_invocationTemplateName:db_bloodline:display': string;
      'db_character_template_through_templateCharacterName:name': string;
      'db_character_template_through_templateCharacterName:chairValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template_through_templateCharacterName:chairValueRule': number;
      'db_character_template_through_templateCharacterName:espritValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template_through_templateCharacterName:espritValueRule': number;
      'db_character_template_through_templateCharacterName:essenceValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template_through_templateCharacterName:essenceValueRule': number;
      'db_character_template_through_templateCharacterName:pvMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template_through_templateCharacterName:pvMaxValueRule': number;
      'db_character_template_through_templateCharacterName:pfMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template_through_templateCharacterName:pfMaxValueRule': number;
      'db_character_template_through_templateCharacterName:ppMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template_through_templateCharacterName:ppMaxValueRule': number;
      'db_character_template_through_templateCharacterName:picture': string;
      'db_character_template_through_templateCharacterName:customData': string;
      'db_character_template_through_templateCharacterName:classeName': string;
      'db_character_template_through_templateCharacterName:bloodlineName': string;
      'db_character_template_through_templateCharacterName:db_classe:name': string;
      'db_character_template_through_templateCharacterName:db_classe:displayMale': string;
      'db_character_template_through_templateCharacterName:db_classe:displayFemale': string;
      'db_character_template_through_templateCharacterName:db_bloodline:name': string;
      'db_character_template_through_templateCharacterName:db_bloodline:display': string;
      'db_skill:allowsPf': boolean;
      'db_skill:allowsPp': boolean;
      'db_skill:stat': 'CHAIR' | 'CUSTOM' | 'EMPIRIQUE' | 'ESPRIT' | 'ESSENCE' | 'FIXE';
      'db_skill:pvCost': number;
      'db_skill:pfCost': number;
      'db_skill:ppCost': number;
      'db_skill:dettesCost': number;
      'db_skill:arcaneCost': number;
      'db_skill:customRolls': string;
      'db_skill:successCalculation': 'AUCUN' | 'CUSTOM' | 'DIVISE' | 'DIVISE_PLUS_1' | 'DOUBLE' | 'DOUBLE_PLUS_1' | 'SIMPLE' | 'SIMPLE_PLUS_1';
      'db_skill:secret': boolean;
      'db_skill:invocationTemplateName': string;
      'db_skill:name': string;
      'db_skill:shortName': string;
      'db_skill:allAttribution': boolean;
      'db_skill:displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'MAGIE' | 'PACIFICATEURS' | 'SOLDATS' | 'STATS';
      'db_skill:position': number;
      'db_skill:display': string;
      'db_skill:isArcanique': boolean;
      'db_skill:description': string;
      'db_skill:longName': string;
      'db_skill:arcanePrimeCost': number;
      'db_skill:precision': string;
      'db_skill:soldatCost': number;
      'db_skill:db_character_template:name': string;
      'db_skill:db_character_template:chairValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:chairValueRule': number;
      'db_skill:db_character_template:espritValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:espritValueRule': number;
      'db_skill:db_character_template:essenceValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:essenceValueRule': number;
      'db_skill:db_character_template:pvMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:pvMaxValueRule': number;
      'db_skill:db_character_template:pfMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:pfMaxValueRule': number;
      'db_skill:db_character_template:ppMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_skill:db_character_template:ppMaxValueRule': number;
      'db_skill:db_character_template:picture': string;
      'db_skill:db_character_template:customData': string;
      'db_skill:db_character_template:classeName': string;
      'db_skill:db_character_template:bloodlineName': string;
      'db_skill:db_character_template:db_classe:name': string;
      'db_skill:db_character_template:db_classe:displayMale': string;
      'db_skill:db_character_template:db_classe:displayFemale': string;
      'db_skill:db_character_template:db_bloodline:name': string;
      'db_skill:db_character_template:db_bloodline:display': string;
    };
  };
  'migrations': {
    plain: {
      'id': number;
      'timestamp': number;
      'name': string;
    };
    nested: {};
    flat: {};
  };
};
