/* eslint-disable */
import {
  CollectionCustomizer,
  TAggregation,
  TConditionTree,
  TPaginatedFilter,
  TPartialRow,
  TSortClause
} from '@forestadmin/agent';

export type DbApotheoseCustomizer = CollectionCustomizer<Schema, 'db_apotheose'>;
export type DbApotheoseRecord = TPartialRow<Schema, 'db_apotheose'>;
export type DbApotheoseConditionTree = TConditionTree<Schema, 'db_apotheose'>;
export type DbApotheoseFilter = TPaginatedFilter<Schema, 'db_apotheose'>;
export type DbApotheoseSortClause = TSortClause<Schema, 'db_apotheose'>;
export type DbApotheoseAggregation = TAggregation<Schema, 'db_apotheose'>;

export type DbBloodlineCustomizer = CollectionCustomizer<Schema, 'db_bloodline'>;
export type DbBloodlineRecord = TPartialRow<Schema, 'db_bloodline'>;
export type DbBloodlineConditionTree = TConditionTree<Schema, 'db_bloodline'>;
export type DbBloodlineFilter = TPaginatedFilter<Schema, 'db_bloodline'>;
export type DbBloodlineSortClause = TSortClause<Schema, 'db_bloodline'>;
export type DbBloodlineAggregation = TAggregation<Schema, 'db_bloodline'>;

export type DbBloodlineProficienciesDbProficiencyCustomizer = CollectionCustomizer<Schema, 'db_bloodline_proficiencies_db_proficiency'>;
export type DbBloodlineProficienciesDbProficiencyRecord = TPartialRow<Schema, 'db_bloodline_proficiencies_db_proficiency'>;
export type DbBloodlineProficienciesDbProficiencyConditionTree = TConditionTree<Schema, 'db_bloodline_proficiencies_db_proficiency'>;
export type DbBloodlineProficienciesDbProficiencyFilter = TPaginatedFilter<Schema, 'db_bloodline_proficiencies_db_proficiency'>;
export type DbBloodlineProficienciesDbProficiencySortClause = TSortClause<Schema, 'db_bloodline_proficiencies_db_proficiency'>;
export type DbBloodlineProficienciesDbProficiencyAggregation = TAggregation<Schema, 'db_bloodline_proficiencies_db_proficiency'>;

export type DbBloodlineSkillsDbSkillCustomizer = CollectionCustomizer<Schema, 'db_bloodline_skills_db_skill'>;
export type DbBloodlineSkillsDbSkillRecord = TPartialRow<Schema, 'db_bloodline_skills_db_skill'>;
export type DbBloodlineSkillsDbSkillConditionTree = TConditionTree<Schema, 'db_bloodline_skills_db_skill'>;
export type DbBloodlineSkillsDbSkillFilter = TPaginatedFilter<Schema, 'db_bloodline_skills_db_skill'>;
export type DbBloodlineSkillsDbSkillSortClause = TSortClause<Schema, 'db_bloodline_skills_db_skill'>;
export type DbBloodlineSkillsDbSkillAggregation = TAggregation<Schema, 'db_bloodline_skills_db_skill'>;

export type DbCharacterCustomizer = CollectionCustomizer<Schema, 'db_character'>;
export type DbCharacterRecord = TPartialRow<Schema, 'db_character'>;
export type DbCharacterConditionTree = TConditionTree<Schema, 'db_character'>;
export type DbCharacterFilter = TPaginatedFilter<Schema, 'db_character'>;
export type DbCharacterSortClause = TSortClause<Schema, 'db_character'>;
export type DbCharacterAggregation = TAggregation<Schema, 'db_character'>;

export type DbCharacterApotheosesDbApotheoseCustomizer = CollectionCustomizer<Schema, 'db_character_apotheoses_db_apotheose'>;
export type DbCharacterApotheosesDbApotheoseRecord = TPartialRow<Schema, 'db_character_apotheoses_db_apotheose'>;
export type DbCharacterApotheosesDbApotheoseConditionTree = TConditionTree<Schema, 'db_character_apotheoses_db_apotheose'>;
export type DbCharacterApotheosesDbApotheoseFilter = TPaginatedFilter<Schema, 'db_character_apotheoses_db_apotheose'>;
export type DbCharacterApotheosesDbApotheoseSortClause = TSortClause<Schema, 'db_character_apotheoses_db_apotheose'>;
export type DbCharacterApotheosesDbApotheoseAggregation = TAggregation<Schema, 'db_character_apotheoses_db_apotheose'>;

export type DbCharacterProficienciesDbProficiencyCustomizer = CollectionCustomizer<Schema, 'db_character_proficiencies_db_proficiency'>;
export type DbCharacterProficienciesDbProficiencyRecord = TPartialRow<Schema, 'db_character_proficiencies_db_proficiency'>;
export type DbCharacterProficienciesDbProficiencyConditionTree = TConditionTree<Schema, 'db_character_proficiencies_db_proficiency'>;
export type DbCharacterProficienciesDbProficiencyFilter = TPaginatedFilter<Schema, 'db_character_proficiencies_db_proficiency'>;
export type DbCharacterProficienciesDbProficiencySortClause = TSortClause<Schema, 'db_character_proficiencies_db_proficiency'>;
export type DbCharacterProficienciesDbProficiencyAggregation = TAggregation<Schema, 'db_character_proficiencies_db_proficiency'>;

export type DbCharacterSkillsDbSkillCustomizer = CollectionCustomizer<Schema, 'db_character_skills_db_skill'>;
export type DbCharacterSkillsDbSkillRecord = TPartialRow<Schema, 'db_character_skills_db_skill'>;
export type DbCharacterSkillsDbSkillConditionTree = TConditionTree<Schema, 'db_character_skills_db_skill'>;
export type DbCharacterSkillsDbSkillFilter = TPaginatedFilter<Schema, 'db_character_skills_db_skill'>;
export type DbCharacterSkillsDbSkillSortClause = TSortClause<Schema, 'db_character_skills_db_skill'>;
export type DbCharacterSkillsDbSkillAggregation = TAggregation<Schema, 'db_character_skills_db_skill'>;

export type DbCharacterTemplateCustomizer = CollectionCustomizer<Schema, 'db_character_template'>;
export type DbCharacterTemplateRecord = TPartialRow<Schema, 'db_character_template'>;
export type DbCharacterTemplateConditionTree = TConditionTree<Schema, 'db_character_template'>;
export type DbCharacterTemplateFilter = TPaginatedFilter<Schema, 'db_character_template'>;
export type DbCharacterTemplateSortClause = TSortClause<Schema, 'db_character_template'>;
export type DbCharacterTemplateAggregation = TAggregation<Schema, 'db_character_template'>;

export type DbCharacterTemplateSkillsDbSkillCustomizer = CollectionCustomizer<Schema, 'db_character_template_skills_db_skill'>;
export type DbCharacterTemplateSkillsDbSkillRecord = TPartialRow<Schema, 'db_character_template_skills_db_skill'>;
export type DbCharacterTemplateSkillsDbSkillConditionTree = TConditionTree<Schema, 'db_character_template_skills_db_skill'>;
export type DbCharacterTemplateSkillsDbSkillFilter = TPaginatedFilter<Schema, 'db_character_template_skills_db_skill'>;
export type DbCharacterTemplateSkillsDbSkillSortClause = TSortClause<Schema, 'db_character_template_skills_db_skill'>;
export type DbCharacterTemplateSkillsDbSkillAggregation = TAggregation<Schema, 'db_character_template_skills_db_skill'>;

export type DbClasseCustomizer = CollectionCustomizer<Schema, 'db_classe'>;
export type DbClasseRecord = TPartialRow<Schema, 'db_classe'>;
export type DbClasseConditionTree = TConditionTree<Schema, 'db_classe'>;
export type DbClasseFilter = TPaginatedFilter<Schema, 'db_classe'>;
export type DbClasseSortClause = TSortClause<Schema, 'db_classe'>;
export type DbClasseAggregation = TAggregation<Schema, 'db_classe'>;

export type DbClasseApotheosesDbApotheoseCustomizer = CollectionCustomizer<Schema, 'db_classe_apotheoses_db_apotheose'>;
export type DbClasseApotheosesDbApotheoseRecord = TPartialRow<Schema, 'db_classe_apotheoses_db_apotheose'>;
export type DbClasseApotheosesDbApotheoseConditionTree = TConditionTree<Schema, 'db_classe_apotheoses_db_apotheose'>;
export type DbClasseApotheosesDbApotheoseFilter = TPaginatedFilter<Schema, 'db_classe_apotheoses_db_apotheose'>;
export type DbClasseApotheosesDbApotheoseSortClause = TSortClause<Schema, 'db_classe_apotheoses_db_apotheose'>;
export type DbClasseApotheosesDbApotheoseAggregation = TAggregation<Schema, 'db_classe_apotheoses_db_apotheose'>;

export type DbClasseProficienciesDbProficiencyCustomizer = CollectionCustomizer<Schema, 'db_classe_proficiencies_db_proficiency'>;
export type DbClasseProficienciesDbProficiencyRecord = TPartialRow<Schema, 'db_classe_proficiencies_db_proficiency'>;
export type DbClasseProficienciesDbProficiencyConditionTree = TConditionTree<Schema, 'db_classe_proficiencies_db_proficiency'>;
export type DbClasseProficienciesDbProficiencyFilter = TPaginatedFilter<Schema, 'db_classe_proficiencies_db_proficiency'>;
export type DbClasseProficienciesDbProficiencySortClause = TSortClause<Schema, 'db_classe_proficiencies_db_proficiency'>;
export type DbClasseProficienciesDbProficiencyAggregation = TAggregation<Schema, 'db_classe_proficiencies_db_proficiency'>;

export type DbClasseSkillsDbSkillCustomizer = CollectionCustomizer<Schema, 'db_classe_skills_db_skill'>;
export type DbClasseSkillsDbSkillRecord = TPartialRow<Schema, 'db_classe_skills_db_skill'>;
export type DbClasseSkillsDbSkillConditionTree = TConditionTree<Schema, 'db_classe_skills_db_skill'>;
export type DbClasseSkillsDbSkillFilter = TPaginatedFilter<Schema, 'db_classe_skills_db_skill'>;
export type DbClasseSkillsDbSkillSortClause = TSortClause<Schema, 'db_classe_skills_db_skill'>;
export type DbClasseSkillsDbSkillAggregation = TAggregation<Schema, 'db_classe_skills_db_skill'>;

export type DbProficiencyCustomizer = CollectionCustomizer<Schema, 'db_proficiency'>;
export type DbProficiencyRecord = TPartialRow<Schema, 'db_proficiency'>;
export type DbProficiencyConditionTree = TConditionTree<Schema, 'db_proficiency'>;
export type DbProficiencyFilter = TPaginatedFilter<Schema, 'db_proficiency'>;
export type DbProficiencySortClause = TSortClause<Schema, 'db_proficiency'>;
export type DbProficiencyAggregation = TAggregation<Schema, 'db_proficiency'>;

export type DbRollCustomizer = CollectionCustomizer<Schema, 'db_roll'>;
export type DbRollRecord = TPartialRow<Schema, 'db_roll'>;
export type DbRollConditionTree = TConditionTree<Schema, 'db_roll'>;
export type DbRollFilter = TPaginatedFilter<Schema, 'db_roll'>;
export type DbRollSortClause = TSortClause<Schema, 'db_roll'>;
export type DbRollAggregation = TAggregation<Schema, 'db_roll'>;

export type DbSessionCustomizer = CollectionCustomizer<Schema, 'db_session'>;
export type DbSessionRecord = TPartialRow<Schema, 'db_session'>;
export type DbSessionConditionTree = TConditionTree<Schema, 'db_session'>;
export type DbSessionFilter = TPaginatedFilter<Schema, 'db_session'>;
export type DbSessionSortClause = TSortClause<Schema, 'db_session'>;
export type DbSessionAggregation = TAggregation<Schema, 'db_session'>;

export type DbSkillCustomizer = CollectionCustomizer<Schema, 'db_skill'>;
export type DbSkillRecord = TPartialRow<Schema, 'db_skill'>;
export type DbSkillConditionTree = TConditionTree<Schema, 'db_skill'>;
export type DbSkillFilter = TPaginatedFilter<Schema, 'db_skill'>;
export type DbSkillSortClause = TSortClause<Schema, 'db_skill'>;
export type DbSkillAggregation = TAggregation<Schema, 'db_skill'>;

export type MigrationsCustomizer = CollectionCustomizer<Schema, 'migrations'>;
export type MigrationsRecord = TPartialRow<Schema, 'migrations'>;
export type MigrationsConditionTree = TConditionTree<Schema, 'migrations'>;
export type MigrationsFilter = TPaginatedFilter<Schema, 'migrations'>;
export type MigrationsSortClause = TSortClause<Schema, 'migrations'>;
export type MigrationsAggregation = TAggregation<Schema, 'migrations'>;


export type Schema = {
  'db_apotheose': {
    plain: {
      'name': string;
      'shortName': string;
      'displayCategory': 'STATS' | 'MAGIE' | 'ARCANES' | 'ARCANES_PRIMES' | 'SOLDATS' | 'PACIFICATEURS';
      'description': string;
      'position': number;
      'minLevel': number;
      'maxLevel': number;
      'cost': number;
      'chairImprovement': number;
      'espritImprovement': number;
      'essenceImprovement': number;
      'arcaneImprovement': boolean;
      'avantage': boolean;
      'apotheoseEffect': string;
    };
    nested: {};
    flat: {};
  };
  'db_bloodline': {
    plain: {
      'name': string;
      'display': string;
    };
    nested: {};
    flat: {};
  };
  'db_bloodline_proficiencies_db_proficiency': {
    plain: {
      'dbBloodlineName': string;
      'dbProficiencyName': string;
    };
    nested: {
      'db_bloodline': Schema['db_bloodline']['plain'] & Schema['db_bloodline']['nested'];
      'db_proficiency': Schema['db_proficiency']['plain'] & Schema['db_proficiency']['nested'];
    };
    flat: {
      'db_bloodline:name': string;
      'db_bloodline:display': string;
      'db_proficiency:name': string;
      'db_proficiency:shortName': string;
      'db_proficiency:displayCategory': 'STATS' | 'MAGIE' | 'ARCANES' | 'ARCANES_PRIMES' | 'SOLDATS' | 'PACIFICATEURS';
      'db_proficiency:description': string;
      'db_proficiency:minLevel': number;
    };
  };
  'db_bloodline_skills_db_skill': {
    plain: {
      'dbBloodlineName': string;
      'dbSkillId': number;
    };
    nested: {
      'db_bloodline': Schema['db_bloodline']['plain'] & Schema['db_bloodline']['nested'];
      'dbSkill': Schema['db_skill']['plain'] & Schema['db_skill']['nested'];
    };
    flat: {
      'db_bloodline:name': string;
      'db_bloodline:display': string;
      'dbSkill:id': number;
      'dbSkill:displayCategory': 'STATS' | 'MAGIE' | 'ARCANES' | 'ARCANES_PRIMES' | 'SOLDATS' | 'PACIFICATEURS';
      'dbSkill:allowsPf': boolean;
      'dbSkill:allowsPp': boolean;
      'dbSkill:stat': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'EMPIRIQUE' | 'CUSTOM';
      'dbSkill:pvCost': number;
      'dbSkill:pfCost': number;
      'dbSkill:ppCost': number;
      'dbSkill:dettesCost': number;
      'dbSkill:arcaneCost': number;
      'dbSkill:arcanePrimeCost': number;
      'dbSkill:customRolls': string;
      'dbSkill:successCalculation': 'AUCUN' | 'SIMPLE' | 'SIMPLE_PLUS_1' | 'DIVISE' | 'DIVISE_PLUS_1' | 'DOUBLE' | 'DOUBLE_PLUS_1' | 'CUSTOM';
      'dbSkill:secret': boolean;
      'dbSkill:invocationTemplateName': string;
      'dbSkill:name': string;
      'dbSkill:shortName': string;
      'dbSkill:longName': string;
      'dbSkill:allAttribution': boolean;
      'dbSkill:position': number;
      'dbSkill:display': string;
      'dbSkill:isArcanique': boolean;
      'dbSkill:isHeal': boolean;
      'dbSkill:description': string;
      'dbSkill:precision': string;
      'dbSkill:soldatCost': number;
      'dbSkill:db_character_template:name': string;
      'dbSkill:db_character_template:chairValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'dbSkill:db_character_template:chairValueRule': number;
      'dbSkill:db_character_template:espritValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'dbSkill:db_character_template:espritValueRule': number;
      'dbSkill:db_character_template:essenceValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'dbSkill:db_character_template:essenceValueRule': number;
      'dbSkill:db_character_template:pvMaxValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'dbSkill:db_character_template:pvMaxValueRule': number;
      'dbSkill:db_character_template:pfMaxValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'dbSkill:db_character_template:pfMaxValueRule': number;
      'dbSkill:db_character_template:ppMaxValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'dbSkill:db_character_template:ppMaxValueRule': number;
      'dbSkill:db_character_template:picture': string;
      'dbSkill:db_character_template:customData': string;
      'dbSkill:db_character_template:classeName': string;
      'dbSkill:db_character_template:bloodlineName': string;
      'dbSkill:db_character_template:db_classe:name': string;
      'dbSkill:db_character_template:db_classe:displayMale': string;
      'dbSkill:db_character_template:db_classe:displayFemale': string;
      'dbSkill:db_character_template:db_bloodline:name': string;
      'dbSkill:db_character_template:db_bloodline:display': string;
    };
  };
  'db_character': {
    plain: {
      'name': string;
      'classeName': string;
      'controlledBy': string;
      'isInvocation': boolean;
      'currentApotheoseName': string;
      'apotheoseState': 'NONE' | 'ALREADY_USED' | 'COST_TO_PAY' | 'COST_PAID';
      'chair': number;
      'esprit': number;
      'essence': number;
      'pv': number;
      'pvMax': number;
      'pf': number;
      'pfMax': number;
      'pp': number;
      'ppMax': number;
      'dettes': number;
      'arcanes': number;
      'arcanesMax': number;
      'arcanePrimes': number;
      'arcanePrimesMax': number;
      'munitions': number;
      'munitionsMax': number;
      'niveau': number;
      'restImproved': boolean;
      'lux': string;
      'umbra': string;
      'secunda': string;
      'notes': string;
      'battleState': 'NONE' | 'ALLIES' | 'ENNEMIES';
      'genre': 'HOMME' | 'FEMME';
      'relance': number;
      'playerName': string;
      'picture': string;
      'pictureApotheose': string;
      'background': string;
      'buttonColor': string;
      'textColor': string;
      'boosted': boolean;
      'bloodlineName': string;
      'customData': string;
      'dailyUse': any;
      'dailyUseMax': any;
    };
    nested: {
      'db_classe': Schema['db_classe']['plain'] & Schema['db_classe']['nested'];
      'db_apotheose': Schema['db_apotheose']['plain'] & Schema['db_apotheose']['nested'];
      'db_bloodline': Schema['db_bloodline']['plain'] & Schema['db_bloodline']['nested'];
    };
    flat: {
      'db_classe:name': string;
      'db_classe:displayMale': string;
      'db_classe:displayFemale': string;
      'db_apotheose:name': string;
      'db_apotheose:shortName': string;
      'db_apotheose:displayCategory': 'STATS' | 'MAGIE' | 'ARCANES' | 'ARCANES_PRIMES' | 'SOLDATS' | 'PACIFICATEURS';
      'db_apotheose:description': string;
      'db_apotheose:position': number;
      'db_apotheose:minLevel': number;
      'db_apotheose:maxLevel': number;
      'db_apotheose:cost': number;
      'db_apotheose:chairImprovement': number;
      'db_apotheose:espritImprovement': number;
      'db_apotheose:essenceImprovement': number;
      'db_apotheose:arcaneImprovement': boolean;
      'db_apotheose:avantage': boolean;
      'db_apotheose:apotheoseEffect': string;
      'db_bloodline:name': string;
      'db_bloodline:display': string;
    };
  };
  'db_character_apotheoses_db_apotheose': {
    plain: {
      'dbCharacterName': string;
      'dbApotheoseName': string;
    };
    nested: {
      'db_character': Schema['db_character']['plain'] & Schema['db_character']['nested'];
      'db_apotheose': Schema['db_apotheose']['plain'] & Schema['db_apotheose']['nested'];
    };
    flat: {
      'db_character:name': string;
      'db_character:classeName': string;
      'db_character:controlledBy': string;
      'db_character:isInvocation': boolean;
      'db_character:currentApotheoseName': string;
      'db_character:apotheoseState': 'NONE' | 'ALREADY_USED' | 'COST_TO_PAY' | 'COST_PAID';
      'db_character:chair': number;
      'db_character:esprit': number;
      'db_character:essence': number;
      'db_character:pv': number;
      'db_character:pvMax': number;
      'db_character:pf': number;
      'db_character:pfMax': number;
      'db_character:pp': number;
      'db_character:ppMax': number;
      'db_character:dettes': number;
      'db_character:arcanes': number;
      'db_character:arcanesMax': number;
      'db_character:arcanePrimes': number;
      'db_character:arcanePrimesMax': number;
      'db_character:munitions': number;
      'db_character:munitionsMax': number;
      'db_character:niveau': number;
      'db_character:restImproved': boolean;
      'db_character:lux': string;
      'db_character:umbra': string;
      'db_character:secunda': string;
      'db_character:notes': string;
      'db_character:battleState': 'NONE' | 'ALLIES' | 'ENNEMIES';
      'db_character:genre': 'HOMME' | 'FEMME';
      'db_character:relance': number;
      'db_character:playerName': string;
      'db_character:picture': string;
      'db_character:pictureApotheose': string;
      'db_character:background': string;
      'db_character:buttonColor': string;
      'db_character:textColor': string;
      'db_character:boosted': boolean;
      'db_character:bloodlineName': string;
      'db_character:customData': string;
      'db_character:dailyUse': any;
      'db_character:dailyUseMax': any;
      'db_character:db_classe:name': string;
      'db_character:db_classe:displayMale': string;
      'db_character:db_classe:displayFemale': string;
      'db_character:db_apotheose:name': string;
      'db_character:db_apotheose:shortName': string;
      'db_character:db_apotheose:displayCategory': 'STATS' | 'MAGIE' | 'ARCANES' | 'ARCANES_PRIMES' | 'SOLDATS' | 'PACIFICATEURS';
      'db_character:db_apotheose:description': string;
      'db_character:db_apotheose:position': number;
      'db_character:db_apotheose:minLevel': number;
      'db_character:db_apotheose:maxLevel': number;
      'db_character:db_apotheose:cost': number;
      'db_character:db_apotheose:chairImprovement': number;
      'db_character:db_apotheose:espritImprovement': number;
      'db_character:db_apotheose:essenceImprovement': number;
      'db_character:db_apotheose:arcaneImprovement': boolean;
      'db_character:db_apotheose:avantage': boolean;
      'db_character:db_apotheose:apotheoseEffect': string;
      'db_character:db_bloodline:name': string;
      'db_character:db_bloodline:display': string;
      'db_apotheose:name': string;
      'db_apotheose:shortName': string;
      'db_apotheose:displayCategory': 'STATS' | 'MAGIE' | 'ARCANES' | 'ARCANES_PRIMES' | 'SOLDATS' | 'PACIFICATEURS';
      'db_apotheose:description': string;
      'db_apotheose:position': number;
      'db_apotheose:minLevel': number;
      'db_apotheose:maxLevel': number;
      'db_apotheose:cost': number;
      'db_apotheose:chairImprovement': number;
      'db_apotheose:espritImprovement': number;
      'db_apotheose:essenceImprovement': number;
      'db_apotheose:arcaneImprovement': boolean;
      'db_apotheose:avantage': boolean;
      'db_apotheose:apotheoseEffect': string;
    };
  };
  'db_character_proficiencies_db_proficiency': {
    plain: {
      'dbCharacterName': string;
      'dbProficiencyName': string;
    };
    nested: {
      'db_character': Schema['db_character']['plain'] & Schema['db_character']['nested'];
      'db_proficiency': Schema['db_proficiency']['plain'] & Schema['db_proficiency']['nested'];
    };
    flat: {
      'db_character:name': string;
      'db_character:classeName': string;
      'db_character:controlledBy': string;
      'db_character:isInvocation': boolean;
      'db_character:currentApotheoseName': string;
      'db_character:apotheoseState': 'NONE' | 'ALREADY_USED' | 'COST_TO_PAY' | 'COST_PAID';
      'db_character:chair': number;
      'db_character:esprit': number;
      'db_character:essence': number;
      'db_character:pv': number;
      'db_character:pvMax': number;
      'db_character:pf': number;
      'db_character:pfMax': number;
      'db_character:pp': number;
      'db_character:ppMax': number;
      'db_character:dettes': number;
      'db_character:arcanes': number;
      'db_character:arcanesMax': number;
      'db_character:arcanePrimes': number;
      'db_character:arcanePrimesMax': number;
      'db_character:munitions': number;
      'db_character:munitionsMax': number;
      'db_character:niveau': number;
      'db_character:restImproved': boolean;
      'db_character:lux': string;
      'db_character:umbra': string;
      'db_character:secunda': string;
      'db_character:notes': string;
      'db_character:battleState': 'NONE' | 'ALLIES' | 'ENNEMIES';
      'db_character:genre': 'HOMME' | 'FEMME';
      'db_character:relance': number;
      'db_character:playerName': string;
      'db_character:picture': string;
      'db_character:pictureApotheose': string;
      'db_character:background': string;
      'db_character:buttonColor': string;
      'db_character:textColor': string;
      'db_character:boosted': boolean;
      'db_character:bloodlineName': string;
      'db_character:customData': string;
      'db_character:dailyUse': any;
      'db_character:dailyUseMax': any;
      'db_character:db_classe:name': string;
      'db_character:db_classe:displayMale': string;
      'db_character:db_classe:displayFemale': string;
      'db_character:db_apotheose:name': string;
      'db_character:db_apotheose:shortName': string;
      'db_character:db_apotheose:displayCategory': 'STATS' | 'MAGIE' | 'ARCANES' | 'ARCANES_PRIMES' | 'SOLDATS' | 'PACIFICATEURS';
      'db_character:db_apotheose:description': string;
      'db_character:db_apotheose:position': number;
      'db_character:db_apotheose:minLevel': number;
      'db_character:db_apotheose:maxLevel': number;
      'db_character:db_apotheose:cost': number;
      'db_character:db_apotheose:chairImprovement': number;
      'db_character:db_apotheose:espritImprovement': number;
      'db_character:db_apotheose:essenceImprovement': number;
      'db_character:db_apotheose:arcaneImprovement': boolean;
      'db_character:db_apotheose:avantage': boolean;
      'db_character:db_apotheose:apotheoseEffect': string;
      'db_character:db_bloodline:name': string;
      'db_character:db_bloodline:display': string;
      'db_proficiency:name': string;
      'db_proficiency:shortName': string;
      'db_proficiency:displayCategory': 'STATS' | 'MAGIE' | 'ARCANES' | 'ARCANES_PRIMES' | 'SOLDATS' | 'PACIFICATEURS';
      'db_proficiency:description': string;
      'db_proficiency:minLevel': number;
    };
  };
  'db_character_skills_db_skill': {
    plain: {
      'dbCharacterName': string;
      'dbSkillId': number;
    };
    nested: {
      'db_character': Schema['db_character']['plain'] & Schema['db_character']['nested'];
      'dbSkill': Schema['db_skill']['plain'] & Schema['db_skill']['nested'];
    };
    flat: {
      'db_character:name': string;
      'db_character:classeName': string;
      'db_character:controlledBy': string;
      'db_character:isInvocation': boolean;
      'db_character:currentApotheoseName': string;
      'db_character:apotheoseState': 'NONE' | 'ALREADY_USED' | 'COST_TO_PAY' | 'COST_PAID';
      'db_character:chair': number;
      'db_character:esprit': number;
      'db_character:essence': number;
      'db_character:pv': number;
      'db_character:pvMax': number;
      'db_character:pf': number;
      'db_character:pfMax': number;
      'db_character:pp': number;
      'db_character:ppMax': number;
      'db_character:dettes': number;
      'db_character:arcanes': number;
      'db_character:arcanesMax': number;
      'db_character:arcanePrimes': number;
      'db_character:arcanePrimesMax': number;
      'db_character:munitions': number;
      'db_character:munitionsMax': number;
      'db_character:niveau': number;
      'db_character:restImproved': boolean;
      'db_character:lux': string;
      'db_character:umbra': string;
      'db_character:secunda': string;
      'db_character:notes': string;
      'db_character:battleState': 'NONE' | 'ALLIES' | 'ENNEMIES';
      'db_character:genre': 'HOMME' | 'FEMME';
      'db_character:relance': number;
      'db_character:playerName': string;
      'db_character:picture': string;
      'db_character:pictureApotheose': string;
      'db_character:background': string;
      'db_character:buttonColor': string;
      'db_character:textColor': string;
      'db_character:boosted': boolean;
      'db_character:bloodlineName': string;
      'db_character:customData': string;
      'db_character:dailyUse': any;
      'db_character:dailyUseMax': any;
      'db_character:db_classe:name': string;
      'db_character:db_classe:displayMale': string;
      'db_character:db_classe:displayFemale': string;
      'db_character:db_apotheose:name': string;
      'db_character:db_apotheose:shortName': string;
      'db_character:db_apotheose:displayCategory': 'STATS' | 'MAGIE' | 'ARCANES' | 'ARCANES_PRIMES' | 'SOLDATS' | 'PACIFICATEURS';
      'db_character:db_apotheose:description': string;
      'db_character:db_apotheose:position': number;
      'db_character:db_apotheose:minLevel': number;
      'db_character:db_apotheose:maxLevel': number;
      'db_character:db_apotheose:cost': number;
      'db_character:db_apotheose:chairImprovement': number;
      'db_character:db_apotheose:espritImprovement': number;
      'db_character:db_apotheose:essenceImprovement': number;
      'db_character:db_apotheose:arcaneImprovement': boolean;
      'db_character:db_apotheose:avantage': boolean;
      'db_character:db_apotheose:apotheoseEffect': string;
      'db_character:db_bloodline:name': string;
      'db_character:db_bloodline:display': string;
      'dbSkill:id': number;
      'dbSkill:displayCategory': 'STATS' | 'MAGIE' | 'ARCANES' | 'ARCANES_PRIMES' | 'SOLDATS' | 'PACIFICATEURS';
      'dbSkill:allowsPf': boolean;
      'dbSkill:allowsPp': boolean;
      'dbSkill:stat': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'EMPIRIQUE' | 'CUSTOM';
      'dbSkill:pvCost': number;
      'dbSkill:pfCost': number;
      'dbSkill:ppCost': number;
      'dbSkill:dettesCost': number;
      'dbSkill:arcaneCost': number;
      'dbSkill:arcanePrimeCost': number;
      'dbSkill:customRolls': string;
      'dbSkill:successCalculation': 'AUCUN' | 'SIMPLE' | 'SIMPLE_PLUS_1' | 'DIVISE' | 'DIVISE_PLUS_1' | 'DOUBLE' | 'DOUBLE_PLUS_1' | 'CUSTOM';
      'dbSkill:secret': boolean;
      'dbSkill:invocationTemplateName': string;
      'dbSkill:name': string;
      'dbSkill:shortName': string;
      'dbSkill:longName': string;
      'dbSkill:allAttribution': boolean;
      'dbSkill:position': number;
      'dbSkill:display': string;
      'dbSkill:isArcanique': boolean;
      'dbSkill:isHeal': boolean;
      'dbSkill:description': string;
      'dbSkill:precision': string;
      'dbSkill:soldatCost': number;
      'dbSkill:db_character_template:name': string;
      'dbSkill:db_character_template:chairValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'dbSkill:db_character_template:chairValueRule': number;
      'dbSkill:db_character_template:espritValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'dbSkill:db_character_template:espritValueRule': number;
      'dbSkill:db_character_template:essenceValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'dbSkill:db_character_template:essenceValueRule': number;
      'dbSkill:db_character_template:pvMaxValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'dbSkill:db_character_template:pvMaxValueRule': number;
      'dbSkill:db_character_template:pfMaxValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'dbSkill:db_character_template:pfMaxValueRule': number;
      'dbSkill:db_character_template:ppMaxValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'dbSkill:db_character_template:ppMaxValueRule': number;
      'dbSkill:db_character_template:picture': string;
      'dbSkill:db_character_template:customData': string;
      'dbSkill:db_character_template:classeName': string;
      'dbSkill:db_character_template:bloodlineName': string;
      'dbSkill:db_character_template:db_classe:name': string;
      'dbSkill:db_character_template:db_classe:displayMale': string;
      'dbSkill:db_character_template:db_classe:displayFemale': string;
      'dbSkill:db_character_template:db_bloodline:name': string;
      'dbSkill:db_character_template:db_bloodline:display': string;
    };
  };
  'db_character_template': {
    plain: {
      'name': string;
      'chairValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'chairValueRule': number;
      'espritValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'espritValueRule': number;
      'essenceValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'essenceValueRule': number;
      'pvMaxValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'pvMaxValueRule': number;
      'pfMaxValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'pfMaxValueRule': number;
      'ppMaxValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'ppMaxValueRule': number;
      'picture': string;
      'customData': string;
      'classeName': string;
      'bloodlineName': string;
    };
    nested: {
      'db_classe': Schema['db_classe']['plain'] & Schema['db_classe']['nested'];
      'db_bloodline': Schema['db_bloodline']['plain'] & Schema['db_bloodline']['nested'];
    };
    flat: {
      'db_classe:name': string;
      'db_classe:displayMale': string;
      'db_classe:displayFemale': string;
      'db_bloodline:name': string;
      'db_bloodline:display': string;
    };
  };
  'db_character_template_skills_db_skill': {
    plain: {
      'dbCharacterTemplateName': string;
      'dbSkillId': number;
    };
    nested: {
      'db_character_template': Schema['db_character_template']['plain'] & Schema['db_character_template']['nested'];
      'dbSkill': Schema['db_skill']['plain'] & Schema['db_skill']['nested'];
    };
    flat: {
      'db_character_template:name': string;
      'db_character_template:chairValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'db_character_template:chairValueRule': number;
      'db_character_template:espritValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'db_character_template:espritValueRule': number;
      'db_character_template:essenceValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'db_character_template:essenceValueRule': number;
      'db_character_template:pvMaxValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'db_character_template:pvMaxValueRule': number;
      'db_character_template:pfMaxValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'db_character_template:pfMaxValueRule': number;
      'db_character_template:ppMaxValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'db_character_template:ppMaxValueRule': number;
      'db_character_template:picture': string;
      'db_character_template:customData': string;
      'db_character_template:classeName': string;
      'db_character_template:bloodlineName': string;
      'db_character_template:db_classe:name': string;
      'db_character_template:db_classe:displayMale': string;
      'db_character_template:db_classe:displayFemale': string;
      'db_character_template:db_bloodline:name': string;
      'db_character_template:db_bloodline:display': string;
      'dbSkill:id': number;
      'dbSkill:displayCategory': 'STATS' | 'MAGIE' | 'ARCANES' | 'ARCANES_PRIMES' | 'SOLDATS' | 'PACIFICATEURS';
      'dbSkill:allowsPf': boolean;
      'dbSkill:allowsPp': boolean;
      'dbSkill:stat': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'EMPIRIQUE' | 'CUSTOM';
      'dbSkill:pvCost': number;
      'dbSkill:pfCost': number;
      'dbSkill:ppCost': number;
      'dbSkill:dettesCost': number;
      'dbSkill:arcaneCost': number;
      'dbSkill:arcanePrimeCost': number;
      'dbSkill:customRolls': string;
      'dbSkill:successCalculation': 'AUCUN' | 'SIMPLE' | 'SIMPLE_PLUS_1' | 'DIVISE' | 'DIVISE_PLUS_1' | 'DOUBLE' | 'DOUBLE_PLUS_1' | 'CUSTOM';
      'dbSkill:secret': boolean;
      'dbSkill:invocationTemplateName': string;
      'dbSkill:name': string;
      'dbSkill:shortName': string;
      'dbSkill:longName': string;
      'dbSkill:allAttribution': boolean;
      'dbSkill:position': number;
      'dbSkill:display': string;
      'dbSkill:isArcanique': boolean;
      'dbSkill:isHeal': boolean;
      'dbSkill:description': string;
      'dbSkill:precision': string;
      'dbSkill:soldatCost': number;
      'dbSkill:db_character_template:name': string;
      'dbSkill:db_character_template:chairValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'dbSkill:db_character_template:chairValueRule': number;
      'dbSkill:db_character_template:espritValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'dbSkill:db_character_template:espritValueRule': number;
      'dbSkill:db_character_template:essenceValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'dbSkill:db_character_template:essenceValueRule': number;
      'dbSkill:db_character_template:pvMaxValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'dbSkill:db_character_template:pvMaxValueRule': number;
      'dbSkill:db_character_template:pfMaxValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'dbSkill:db_character_template:pfMaxValueRule': number;
      'dbSkill:db_character_template:ppMaxValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'dbSkill:db_character_template:ppMaxValueRule': number;
      'dbSkill:db_character_template:picture': string;
      'dbSkill:db_character_template:customData': string;
      'dbSkill:db_character_template:classeName': string;
      'dbSkill:db_character_template:bloodlineName': string;
      'dbSkill:db_character_template:db_classe:name': string;
      'dbSkill:db_character_template:db_classe:displayMale': string;
      'dbSkill:db_character_template:db_classe:displayFemale': string;
      'dbSkill:db_character_template:db_bloodline:name': string;
      'dbSkill:db_character_template:db_bloodline:display': string;
    };
  };
  'db_classe': {
    plain: {
      'name': string;
      'displayMale': string;
      'displayFemale': string;
    };
    nested: {};
    flat: {};
  };
  'db_classe_apotheoses_db_apotheose': {
    plain: {
      'dbClasseName': string;
      'dbApotheoseName': string;
    };
    nested: {
      'db_classe': Schema['db_classe']['plain'] & Schema['db_classe']['nested'];
      'db_apotheose': Schema['db_apotheose']['plain'] & Schema['db_apotheose']['nested'];
    };
    flat: {
      'db_classe:name': string;
      'db_classe:displayMale': string;
      'db_classe:displayFemale': string;
      'db_apotheose:name': string;
      'db_apotheose:shortName': string;
      'db_apotheose:displayCategory': 'STATS' | 'MAGIE' | 'ARCANES' | 'ARCANES_PRIMES' | 'SOLDATS' | 'PACIFICATEURS';
      'db_apotheose:description': string;
      'db_apotheose:position': number;
      'db_apotheose:minLevel': number;
      'db_apotheose:maxLevel': number;
      'db_apotheose:cost': number;
      'db_apotheose:chairImprovement': number;
      'db_apotheose:espritImprovement': number;
      'db_apotheose:essenceImprovement': number;
      'db_apotheose:arcaneImprovement': boolean;
      'db_apotheose:avantage': boolean;
      'db_apotheose:apotheoseEffect': string;
    };
  };
  'db_classe_proficiencies_db_proficiency': {
    plain: {
      'dbClasseName': string;
      'dbProficiencyName': string;
    };
    nested: {
      'db_classe': Schema['db_classe']['plain'] & Schema['db_classe']['nested'];
      'db_proficiency': Schema['db_proficiency']['plain'] & Schema['db_proficiency']['nested'];
    };
    flat: {
      'db_classe:name': string;
      'db_classe:displayMale': string;
      'db_classe:displayFemale': string;
      'db_proficiency:name': string;
      'db_proficiency:shortName': string;
      'db_proficiency:displayCategory': 'STATS' | 'MAGIE' | 'ARCANES' | 'ARCANES_PRIMES' | 'SOLDATS' | 'PACIFICATEURS';
      'db_proficiency:description': string;
      'db_proficiency:minLevel': number;
    };
  };
  'db_classe_skills_db_skill': {
    plain: {
      'dbClasseName': string;
      'dbSkillId': number;
    };
    nested: {
      'db_classe': Schema['db_classe']['plain'] & Schema['db_classe']['nested'];
      'dbSkill': Schema['db_skill']['plain'] & Schema['db_skill']['nested'];
    };
    flat: {
      'db_classe:name': string;
      'db_classe:displayMale': string;
      'db_classe:displayFemale': string;
      'dbSkill:id': number;
      'dbSkill:displayCategory': 'STATS' | 'MAGIE' | 'ARCANES' | 'ARCANES_PRIMES' | 'SOLDATS' | 'PACIFICATEURS';
      'dbSkill:allowsPf': boolean;
      'dbSkill:allowsPp': boolean;
      'dbSkill:stat': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'EMPIRIQUE' | 'CUSTOM';
      'dbSkill:pvCost': number;
      'dbSkill:pfCost': number;
      'dbSkill:ppCost': number;
      'dbSkill:dettesCost': number;
      'dbSkill:arcaneCost': number;
      'dbSkill:arcanePrimeCost': number;
      'dbSkill:customRolls': string;
      'dbSkill:successCalculation': 'AUCUN' | 'SIMPLE' | 'SIMPLE_PLUS_1' | 'DIVISE' | 'DIVISE_PLUS_1' | 'DOUBLE' | 'DOUBLE_PLUS_1' | 'CUSTOM';
      'dbSkill:secret': boolean;
      'dbSkill:invocationTemplateName': string;
      'dbSkill:name': string;
      'dbSkill:shortName': string;
      'dbSkill:longName': string;
      'dbSkill:allAttribution': boolean;
      'dbSkill:position': number;
      'dbSkill:display': string;
      'dbSkill:isArcanique': boolean;
      'dbSkill:isHeal': boolean;
      'dbSkill:description': string;
      'dbSkill:precision': string;
      'dbSkill:soldatCost': number;
      'dbSkill:db_character_template:name': string;
      'dbSkill:db_character_template:chairValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'dbSkill:db_character_template:chairValueRule': number;
      'dbSkill:db_character_template:espritValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'dbSkill:db_character_template:espritValueRule': number;
      'dbSkill:db_character_template:essenceValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'dbSkill:db_character_template:essenceValueRule': number;
      'dbSkill:db_character_template:pvMaxValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'dbSkill:db_character_template:pvMaxValueRule': number;
      'dbSkill:db_character_template:pfMaxValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'dbSkill:db_character_template:pfMaxValueRule': number;
      'dbSkill:db_character_template:ppMaxValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'dbSkill:db_character_template:ppMaxValueRule': number;
      'dbSkill:db_character_template:picture': string;
      'dbSkill:db_character_template:customData': string;
      'dbSkill:db_character_template:classeName': string;
      'dbSkill:db_character_template:bloodlineName': string;
      'dbSkill:db_character_template:db_classe:name': string;
      'dbSkill:db_character_template:db_classe:displayMale': string;
      'dbSkill:db_character_template:db_classe:displayFemale': string;
      'dbSkill:db_character_template:db_bloodline:name': string;
      'dbSkill:db_character_template:db_bloodline:display': string;
    };
  };
  'db_proficiency': {
    plain: {
      'name': string;
      'shortName': string;
      'displayCategory': 'STATS' | 'MAGIE' | 'ARCANES' | 'ARCANES_PRIMES' | 'SOLDATS' | 'PACIFICATEURS';
      'description': string;
      'minLevel': number;
    };
    nested: {};
    flat: {};
  };
  'db_roll': {
    plain: {
      'id': number;
      'rollerName': string;
      'date': string;
      'stat': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'EMPIRIQUE' | 'CUSTOM';
      'secret': boolean;
      'focus': boolean;
      'power': boolean;
      'proficiency': boolean;
      'bonus': number;
      'malus': number;
      'result': string;
      'success': number;
      'juge12': number;
      'juge34': number;
      'picture': string;
      'illustration': string;
      'data': string;
      'empiriqueRoll': string;
      'resistRoll': string;
      'display': string;
      'healPoint': number;
    };
    nested: {
      'db_character': Schema['db_character']['plain'] & Schema['db_character']['nested'];
    };
    flat: {
      'db_character:name': string;
      'db_character:classeName': string;
      'db_character:controlledBy': string;
      'db_character:isInvocation': boolean;
      'db_character:currentApotheoseName': string;
      'db_character:apotheoseState': 'NONE' | 'ALREADY_USED' | 'COST_TO_PAY' | 'COST_PAID';
      'db_character:chair': number;
      'db_character:esprit': number;
      'db_character:essence': number;
      'db_character:pv': number;
      'db_character:pvMax': number;
      'db_character:pf': number;
      'db_character:pfMax': number;
      'db_character:pp': number;
      'db_character:ppMax': number;
      'db_character:dettes': number;
      'db_character:arcanes': number;
      'db_character:arcanesMax': number;
      'db_character:arcanePrimes': number;
      'db_character:arcanePrimesMax': number;
      'db_character:munitions': number;
      'db_character:munitionsMax': number;
      'db_character:niveau': number;
      'db_character:restImproved': boolean;
      'db_character:lux': string;
      'db_character:umbra': string;
      'db_character:secunda': string;
      'db_character:notes': string;
      'db_character:battleState': 'NONE' | 'ALLIES' | 'ENNEMIES';
      'db_character:genre': 'HOMME' | 'FEMME';
      'db_character:relance': number;
      'db_character:playerName': string;
      'db_character:picture': string;
      'db_character:pictureApotheose': string;
      'db_character:background': string;
      'db_character:buttonColor': string;
      'db_character:textColor': string;
      'db_character:boosted': boolean;
      'db_character:bloodlineName': string;
      'db_character:customData': string;
      'db_character:dailyUse': any;
      'db_character:dailyUseMax': any;
      'db_character:db_classe:name': string;
      'db_character:db_classe:displayMale': string;
      'db_character:db_classe:displayFemale': string;
      'db_character:db_apotheose:name': string;
      'db_character:db_apotheose:shortName': string;
      'db_character:db_apotheose:displayCategory': 'STATS' | 'MAGIE' | 'ARCANES' | 'ARCANES_PRIMES' | 'SOLDATS' | 'PACIFICATEURS';
      'db_character:db_apotheose:description': string;
      'db_character:db_apotheose:position': number;
      'db_character:db_apotheose:minLevel': number;
      'db_character:db_apotheose:maxLevel': number;
      'db_character:db_apotheose:cost': number;
      'db_character:db_apotheose:chairImprovement': number;
      'db_character:db_apotheose:espritImprovement': number;
      'db_character:db_apotheose:essenceImprovement': number;
      'db_character:db_apotheose:arcaneImprovement': boolean;
      'db_character:db_apotheose:avantage': boolean;
      'db_character:db_apotheose:apotheoseEffect': string;
      'db_character:db_bloodline:name': string;
      'db_character:db_bloodline:display': string;
    };
  };
  'db_session': {
    plain: {
      'id': number;
      'chaos': '0' | '15' | '30' | '45' | '60' | '75';
      'nature': 'LEVEL_0_PAUVRE' | 'LEVEL_1_RARE' | 'LEVEL_2_PRESENTE' | 'LEVEL_3_ABONDANTE' | 'LEVEL_4_RICHE' | 'LEVEL_5_DOMINANTE';
      'baseRest': number;
      'improvedRest': number;
    };
    nested: {};
    flat: {};
  };
  'db_skill': {
    plain: {
      'id': number;
      'displayCategory': 'STATS' | 'MAGIE' | 'ARCANES' | 'ARCANES_PRIMES' | 'SOLDATS' | 'PACIFICATEURS';
      'allowsPf': boolean;
      'allowsPp': boolean;
      'stat': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'EMPIRIQUE' | 'CUSTOM';
      'pvCost': number;
      'pfCost': number;
      'ppCost': number;
      'dettesCost': number;
      'arcaneCost': number;
      'arcanePrimeCost': number;
      'customRolls': string;
      'successCalculation': 'AUCUN' | 'SIMPLE' | 'SIMPLE_PLUS_1' | 'DIVISE' | 'DIVISE_PLUS_1' | 'DOUBLE' | 'DOUBLE_PLUS_1' | 'CUSTOM';
      'secret': boolean;
      'invocationTemplateName': string;
      'name': string;
      'shortName': string;
      'longName': string;
      'allAttribution': boolean;
      'position': number;
      'display': string;
      'isArcanique': boolean;
      'isHeal': boolean;
      'description': string;
      'precision': string;
      'soldatCost': number;
    };
    nested: {
      'db_character_template': Schema['db_character_template']['plain'] & Schema['db_character_template']['nested'];
    };
    flat: {
      'db_character_template:name': string;
      'db_character_template:chairValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'db_character_template:chairValueRule': number;
      'db_character_template:espritValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'db_character_template:espritValueRule': number;
      'db_character_template:essenceValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'db_character_template:essenceValueRule': number;
      'db_character_template:pvMaxValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'db_character_template:pvMaxValueRule': number;
      'db_character_template:pfMaxValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'db_character_template:pfMaxValueRule': number;
      'db_character_template:ppMaxValueReferential': 'FIXE' | 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'SUCCESS';
      'db_character_template:ppMaxValueRule': number;
      'db_character_template:picture': string;
      'db_character_template:customData': string;
      'db_character_template:classeName': string;
      'db_character_template:bloodlineName': string;
      'db_character_template:db_classe:name': string;
      'db_character_template:db_classe:displayMale': string;
      'db_character_template:db_classe:displayFemale': string;
      'db_character_template:db_bloodline:name': string;
      'db_character_template:db_bloodline:display': string;
    };
  };
  'migrations': {
    plain: {
      'id': number;
      'timestamp': number;
      'name': string;
    };
    nested: {};
    flat: {};
  };
};
