/* eslint-disable */
import {
  CollectionCustomizer,
  TAggregation,
  TConditionTree,
  TPaginatedFilter,
  TPartialRow,
  TSortClause
} from '@forestadmin/agent';

export type ConstellationCustomizer = CollectionCustomizer<Schema, 'Constellation'>;
export type ConstellationRecord = TPartialRow<Schema, 'Constellation'>;
export type ConstellationConditionTree = TConditionTree<Schema, 'Constellation'>;
export type ConstellationFilter = TPaginatedFilter<Schema, 'Constellation'>;
export type ConstellationSortClause = TSortClause<Schema, 'Constellation'>;
export type ConstellationAggregation = TAggregation<Schema, 'Constellation'>;

export type EventCustomizer = CollectionCustomizer<Schema, 'Event'>;
export type EventRecord = TPartialRow<Schema, 'Event'>;
export type EventConditionTree = TConditionTree<Schema, 'Event'>;
export type EventFilter = TPaginatedFilter<Schema, 'Event'>;
export type EventSortClause = TSortClause<Schema, 'Event'>;
export type EventAggregation = TAggregation<Schema, 'Event'>;

export type JoueuseCustomizer = CollectionCustomizer<Schema, 'Joueuse'>;
export type JoueuseRecord = TPartialRow<Schema, 'Joueuse'>;
export type JoueuseConditionTree = TConditionTree<Schema, 'Joueuse'>;
export type JoueuseFilter = TPaginatedFilter<Schema, 'Joueuse'>;
export type JoueuseSortClause = TSortClause<Schema, 'Joueuse'>;
export type JoueuseAggregation = TAggregation<Schema, 'Joueuse'>;

export type MessageCustomizer = CollectionCustomizer<Schema, 'Message'>;
export type MessageRecord = TPartialRow<Schema, 'Message'>;
export type MessageConditionTree = TConditionTree<Schema, 'Message'>;
export type MessageFilter = TPaginatedFilter<Schema, 'Message'>;
export type MessageSortClause = TSortClause<Schema, 'Message'>;
export type MessageAggregation = TAggregation<Schema, 'Message'>;

export type ModelMessageCustomizer = CollectionCustomizer<Schema, 'ModelMessage'>;
export type ModelMessageRecord = TPartialRow<Schema, 'ModelMessage'>;
export type ModelMessageConditionTree = TConditionTree<Schema, 'ModelMessage'>;
export type ModelMessageFilter = TPaginatedFilter<Schema, 'ModelMessage'>;
export type ModelMessageSortClause = TSortClause<Schema, 'ModelMessage'>;
export type ModelMessageAggregation = TAggregation<Schema, 'ModelMessage'>;

export type ScenarioCustomizer = CollectionCustomizer<Schema, 'Scenario'>;
export type ScenarioRecord = TPartialRow<Schema, 'Scenario'>;
export type ScenarioConditionTree = TConditionTree<Schema, 'Scenario'>;
export type ScenarioFilter = TPaginatedFilter<Schema, 'Scenario'>;
export type ScenarioSortClause = TSortClause<Schema, 'Scenario'>;
export type ScenarioAggregation = TAggregation<Schema, 'Scenario'>;

export type DbApotheoseCustomizer = CollectionCustomizer<Schema, 'db_apotheose'>;
export type DbApotheoseRecord = TPartialRow<Schema, 'db_apotheose'>;
export type DbApotheoseConditionTree = TConditionTree<Schema, 'db_apotheose'>;
export type DbApotheoseFilter = TPaginatedFilter<Schema, 'db_apotheose'>;
export type DbApotheoseSortClause = TSortClause<Schema, 'db_apotheose'>;
export type DbApotheoseAggregation = TAggregation<Schema, 'db_apotheose'>;

export type DbBloodlineCustomizer = CollectionCustomizer<Schema, 'db_bloodline'>;
export type DbBloodlineRecord = TPartialRow<Schema, 'db_bloodline'>;
export type DbBloodlineConditionTree = TConditionTree<Schema, 'db_bloodline'>;
export type DbBloodlineFilter = TPaginatedFilter<Schema, 'db_bloodline'>;
export type DbBloodlineSortClause = TSortClause<Schema, 'db_bloodline'>;
export type DbBloodlineAggregation = TAggregation<Schema, 'db_bloodline'>;

export type DbBloodlineProficienciesDbProficiencyCustomizer = CollectionCustomizer<Schema, 'db_bloodline_proficiencies_db_proficiency'>;
export type DbBloodlineProficienciesDbProficiencyRecord = TPartialRow<Schema, 'db_bloodline_proficiencies_db_proficiency'>;
export type DbBloodlineProficienciesDbProficiencyConditionTree = TConditionTree<Schema, 'db_bloodline_proficiencies_db_proficiency'>;
export type DbBloodlineProficienciesDbProficiencyFilter = TPaginatedFilter<Schema, 'db_bloodline_proficiencies_db_proficiency'>;
export type DbBloodlineProficienciesDbProficiencySortClause = TSortClause<Schema, 'db_bloodline_proficiencies_db_proficiency'>;
export type DbBloodlineProficienciesDbProficiencyAggregation = TAggregation<Schema, 'db_bloodline_proficiencies_db_proficiency'>;

export type DbBloodlineSkillsDbSkillCustomizer = CollectionCustomizer<Schema, 'db_bloodline_skills_db_skill'>;
export type DbBloodlineSkillsDbSkillRecord = TPartialRow<Schema, 'db_bloodline_skills_db_skill'>;
export type DbBloodlineSkillsDbSkillConditionTree = TConditionTree<Schema, 'db_bloodline_skills_db_skill'>;
export type DbBloodlineSkillsDbSkillFilter = TPaginatedFilter<Schema, 'db_bloodline_skills_db_skill'>;
export type DbBloodlineSkillsDbSkillSortClause = TSortClause<Schema, 'db_bloodline_skills_db_skill'>;
export type DbBloodlineSkillsDbSkillAggregation = TAggregation<Schema, 'db_bloodline_skills_db_skill'>;

export type DbCharacterCustomizer = CollectionCustomizer<Schema, 'db_character'>;
export type DbCharacterRecord = TPartialRow<Schema, 'db_character'>;
export type DbCharacterConditionTree = TConditionTree<Schema, 'db_character'>;
export type DbCharacterFilter = TPaginatedFilter<Schema, 'db_character'>;
export type DbCharacterSortClause = TSortClause<Schema, 'db_character'>;
export type DbCharacterAggregation = TAggregation<Schema, 'db_character'>;

export type DbCharacterApotheosesDbApotheoseCustomizer = CollectionCustomizer<Schema, 'db_character_apotheoses_db_apotheose'>;
export type DbCharacterApotheosesDbApotheoseRecord = TPartialRow<Schema, 'db_character_apotheoses_db_apotheose'>;
export type DbCharacterApotheosesDbApotheoseConditionTree = TConditionTree<Schema, 'db_character_apotheoses_db_apotheose'>;
export type DbCharacterApotheosesDbApotheoseFilter = TPaginatedFilter<Schema, 'db_character_apotheoses_db_apotheose'>;
export type DbCharacterApotheosesDbApotheoseSortClause = TSortClause<Schema, 'db_character_apotheoses_db_apotheose'>;
export type DbCharacterApotheosesDbApotheoseAggregation = TAggregation<Schema, 'db_character_apotheoses_db_apotheose'>;

export type DbCharacterProficienciesDbProficiencyCustomizer = CollectionCustomizer<Schema, 'db_character_proficiencies_db_proficiency'>;
export type DbCharacterProficienciesDbProficiencyRecord = TPartialRow<Schema, 'db_character_proficiencies_db_proficiency'>;
export type DbCharacterProficienciesDbProficiencyConditionTree = TConditionTree<Schema, 'db_character_proficiencies_db_proficiency'>;
export type DbCharacterProficienciesDbProficiencyFilter = TPaginatedFilter<Schema, 'db_character_proficiencies_db_proficiency'>;
export type DbCharacterProficienciesDbProficiencySortClause = TSortClause<Schema, 'db_character_proficiencies_db_proficiency'>;
export type DbCharacterProficienciesDbProficiencyAggregation = TAggregation<Schema, 'db_character_proficiencies_db_proficiency'>;

export type DbCharacterSkillsDbSkillCustomizer = CollectionCustomizer<Schema, 'db_character_skills_db_skill'>;
export type DbCharacterSkillsDbSkillRecord = TPartialRow<Schema, 'db_character_skills_db_skill'>;
export type DbCharacterSkillsDbSkillConditionTree = TConditionTree<Schema, 'db_character_skills_db_skill'>;
export type DbCharacterSkillsDbSkillFilter = TPaginatedFilter<Schema, 'db_character_skills_db_skill'>;
export type DbCharacterSkillsDbSkillSortClause = TSortClause<Schema, 'db_character_skills_db_skill'>;
export type DbCharacterSkillsDbSkillAggregation = TAggregation<Schema, 'db_character_skills_db_skill'>;

export type DbCharacterTemplateCustomizer = CollectionCustomizer<Schema, 'db_character_template'>;
export type DbCharacterTemplateRecord = TPartialRow<Schema, 'db_character_template'>;
export type DbCharacterTemplateConditionTree = TConditionTree<Schema, 'db_character_template'>;
export type DbCharacterTemplateFilter = TPaginatedFilter<Schema, 'db_character_template'>;
export type DbCharacterTemplateSortClause = TSortClause<Schema, 'db_character_template'>;
export type DbCharacterTemplateAggregation = TAggregation<Schema, 'db_character_template'>;

export type DbCharacterTemplateSkillsDbSkillCustomizer = CollectionCustomizer<Schema, 'db_character_template_skills_db_skill'>;
export type DbCharacterTemplateSkillsDbSkillRecord = TPartialRow<Schema, 'db_character_template_skills_db_skill'>;
export type DbCharacterTemplateSkillsDbSkillConditionTree = TConditionTree<Schema, 'db_character_template_skills_db_skill'>;
export type DbCharacterTemplateSkillsDbSkillFilter = TPaginatedFilter<Schema, 'db_character_template_skills_db_skill'>;
export type DbCharacterTemplateSkillsDbSkillSortClause = TSortClause<Schema, 'db_character_template_skills_db_skill'>;
export type DbCharacterTemplateSkillsDbSkillAggregation = TAggregation<Schema, 'db_character_template_skills_db_skill'>;

export type DbClasseCustomizer = CollectionCustomizer<Schema, 'db_classe'>;
export type DbClasseRecord = TPartialRow<Schema, 'db_classe'>;
export type DbClasseConditionTree = TConditionTree<Schema, 'db_classe'>;
export type DbClasseFilter = TPaginatedFilter<Schema, 'db_classe'>;
export type DbClasseSortClause = TSortClause<Schema, 'db_classe'>;
export type DbClasseAggregation = TAggregation<Schema, 'db_classe'>;

export type DbClasseApotheosesDbApotheoseCustomizer = CollectionCustomizer<Schema, 'db_classe_apotheoses_db_apotheose'>;
export type DbClasseApotheosesDbApotheoseRecord = TPartialRow<Schema, 'db_classe_apotheoses_db_apotheose'>;
export type DbClasseApotheosesDbApotheoseConditionTree = TConditionTree<Schema, 'db_classe_apotheoses_db_apotheose'>;
export type DbClasseApotheosesDbApotheoseFilter = TPaginatedFilter<Schema, 'db_classe_apotheoses_db_apotheose'>;
export type DbClasseApotheosesDbApotheoseSortClause = TSortClause<Schema, 'db_classe_apotheoses_db_apotheose'>;
export type DbClasseApotheosesDbApotheoseAggregation = TAggregation<Schema, 'db_classe_apotheoses_db_apotheose'>;

export type DbClasseProficienciesDbProficiencyCustomizer = CollectionCustomizer<Schema, 'db_classe_proficiencies_db_proficiency'>;
export type DbClasseProficienciesDbProficiencyRecord = TPartialRow<Schema, 'db_classe_proficiencies_db_proficiency'>;
export type DbClasseProficienciesDbProficiencyConditionTree = TConditionTree<Schema, 'db_classe_proficiencies_db_proficiency'>;
export type DbClasseProficienciesDbProficiencyFilter = TPaginatedFilter<Schema, 'db_classe_proficiencies_db_proficiency'>;
export type DbClasseProficienciesDbProficiencySortClause = TSortClause<Schema, 'db_classe_proficiencies_db_proficiency'>;
export type DbClasseProficienciesDbProficiencyAggregation = TAggregation<Schema, 'db_classe_proficiencies_db_proficiency'>;

export type DbClasseSkillsDbSkillCustomizer = CollectionCustomizer<Schema, 'db_classe_skills_db_skill'>;
export type DbClasseSkillsDbSkillRecord = TPartialRow<Schema, 'db_classe_skills_db_skill'>;
export type DbClasseSkillsDbSkillConditionTree = TConditionTree<Schema, 'db_classe_skills_db_skill'>;
export type DbClasseSkillsDbSkillFilter = TPaginatedFilter<Schema, 'db_classe_skills_db_skill'>;
export type DbClasseSkillsDbSkillSortClause = TSortClause<Schema, 'db_classe_skills_db_skill'>;
export type DbClasseSkillsDbSkillAggregation = TAggregation<Schema, 'db_classe_skills_db_skill'>;

export type DbEntryCustomizer = CollectionCustomizer<Schema, 'db_entry'>;
export type DbEntryRecord = TPartialRow<Schema, 'db_entry'>;
export type DbEntryConditionTree = TConditionTree<Schema, 'db_entry'>;
export type DbEntryFilter = TPaginatedFilter<Schema, 'db_entry'>;
export type DbEntrySortClause = TSortClause<Schema, 'db_entry'>;
export type DbEntryAggregation = TAggregation<Schema, 'db_entry'>;

export type DbKnowledgeCustomizer = CollectionCustomizer<Schema, 'db_knowledge'>;
export type DbKnowledgeRecord = TPartialRow<Schema, 'db_knowledge'>;
export type DbKnowledgeConditionTree = TConditionTree<Schema, 'db_knowledge'>;
export type DbKnowledgeFilter = TPaginatedFilter<Schema, 'db_knowledge'>;
export type DbKnowledgeSortClause = TSortClause<Schema, 'db_knowledge'>;
export type DbKnowledgeAggregation = TAggregation<Schema, 'db_knowledge'>;

export type DbProficiencyCustomizer = CollectionCustomizer<Schema, 'db_proficiency'>;
export type DbProficiencyRecord = TPartialRow<Schema, 'db_proficiency'>;
export type DbProficiencyConditionTree = TConditionTree<Schema, 'db_proficiency'>;
export type DbProficiencyFilter = TPaginatedFilter<Schema, 'db_proficiency'>;
export type DbProficiencySortClause = TSortClause<Schema, 'db_proficiency'>;
export type DbProficiencyAggregation = TAggregation<Schema, 'db_proficiency'>;

export type DbRollCustomizer = CollectionCustomizer<Schema, 'db_roll'>;
export type DbRollRecord = TPartialRow<Schema, 'db_roll'>;
export type DbRollConditionTree = TConditionTree<Schema, 'db_roll'>;
export type DbRollFilter = TPaginatedFilter<Schema, 'db_roll'>;
export type DbRollSortClause = TSortClause<Schema, 'db_roll'>;
export type DbRollAggregation = TAggregation<Schema, 'db_roll'>;

export type DbSessionCustomizer = CollectionCustomizer<Schema, 'db_session'>;
export type DbSessionRecord = TPartialRow<Schema, 'db_session'>;
export type DbSessionConditionTree = TConditionTree<Schema, 'db_session'>;
export type DbSessionFilter = TPaginatedFilter<Schema, 'db_session'>;
export type DbSessionSortClause = TSortClause<Schema, 'db_session'>;
export type DbSessionAggregation = TAggregation<Schema, 'db_session'>;

export type DbSkillCustomizer = CollectionCustomizer<Schema, 'db_skill'>;
export type DbSkillRecord = TPartialRow<Schema, 'db_skill'>;
export type DbSkillConditionTree = TConditionTree<Schema, 'db_skill'>;
export type DbSkillFilter = TPaginatedFilter<Schema, 'db_skill'>;
export type DbSkillSortClause = TSortClause<Schema, 'db_skill'>;
export type DbSkillAggregation = TAggregation<Schema, 'db_skill'>;

export type DbStatCustomizer = CollectionCustomizer<Schema, 'db_stat'>;
export type DbStatRecord = TPartialRow<Schema, 'db_stat'>;
export type DbStatConditionTree = TConditionTree<Schema, 'db_stat'>;
export type DbStatFilter = TPaginatedFilter<Schema, 'db_stat'>;
export type DbStatSortClause = TSortClause<Schema, 'db_stat'>;
export type DbStatAggregation = TAggregation<Schema, 'db_stat'>;

export type DbWizardCustomizer = CollectionCustomizer<Schema, 'db_wizard'>;
export type DbWizardRecord = TPartialRow<Schema, 'db_wizard'>;
export type DbWizardConditionTree = TConditionTree<Schema, 'db_wizard'>;
export type DbWizardFilter = TPaginatedFilter<Schema, 'db_wizard'>;
export type DbWizardSortClause = TSortClause<Schema, 'db_wizard'>;
export type DbWizardAggregation = TAggregation<Schema, 'db_wizard'>;

export type DbWizardKnowledgeCustomizer = CollectionCustomizer<Schema, 'db_wizard_knowledge'>;
export type DbWizardKnowledgeRecord = TPartialRow<Schema, 'db_wizard_knowledge'>;
export type DbWizardKnowledgeConditionTree = TConditionTree<Schema, 'db_wizard_knowledge'>;
export type DbWizardKnowledgeFilter = TPaginatedFilter<Schema, 'db_wizard_knowledge'>;
export type DbWizardKnowledgeSortClause = TSortClause<Schema, 'db_wizard_knowledge'>;
export type DbWizardKnowledgeAggregation = TAggregation<Schema, 'db_wizard_knowledge'>;

export type DbWizardStatCustomizer = CollectionCustomizer<Schema, 'db_wizard_stat'>;
export type DbWizardStatRecord = TPartialRow<Schema, 'db_wizard_stat'>;
export type DbWizardStatConditionTree = TConditionTree<Schema, 'db_wizard_stat'>;
export type DbWizardStatFilter = TPaginatedFilter<Schema, 'db_wizard_stat'>;
export type DbWizardStatSortClause = TSortClause<Schema, 'db_wizard_stat'>;
export type DbWizardStatAggregation = TAggregation<Schema, 'db_wizard_stat'>;

export type MigrationsCustomizer = CollectionCustomizer<Schema, 'migrations'>;
export type MigrationsRecord = TPartialRow<Schema, 'migrations'>;
export type MigrationsConditionTree = TConditionTree<Schema, 'migrations'>;
export type MigrationsFilter = TPaginatedFilter<Schema, 'migrations'>;
export type MigrationsSortClause = TSortClause<Schema, 'migrations'>;
export type MigrationsAggregation = TAggregation<Schema, 'migrations'>;


export type Schema = {
  'Constellation': {
    plain: {
      'id': string;
      'name': string;
      'pictureUrl': string;
      'pictureUrlRevealed': string;
      'revealed': boolean;
      'realName': string;
      'isStarStream': boolean;
      'sponsor': boolean;
    };
    nested: {};
    flat: {};
  };
  'db_apotheose': {
    plain: {
      'name': string;
      'shortName': string;
      'displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'BONUS' | 'MAGIE' | 'PACIFICATEURS' | 'PAROLIERS' | 'SOLDATS' | 'SOUTIENS' | 'STATS' | 'TECHNOMANCIE';
      'description': string;
      'position': number;
      'minLevel': number;
      'maxLevel': number;
      'cost': number;
      'chairImprovement': number;
      'espritImprovement': number;
      'essenceImprovement': number;
      'arcaneImprovement': boolean;
      'avantage': boolean;
      'apotheoseEffect': string;
    };
    nested: {};
    flat: {};
  };
  'db_bloodline': {
    plain: {
      'name': string;
      'display': string;
    };
    nested: {};
    flat: {};
  };
  'db_bloodline_proficiencies_db_proficiency': {
    plain: {
      'dbBloodlineName': string;
      'dbProficiencyName': string;
    };
    nested: {
      'db_bloodline': Schema['db_bloodline']['plain'] & Schema['db_bloodline']['nested'];
      'db_proficiency': Schema['db_proficiency']['plain'] & Schema['db_proficiency']['nested'];
    };
    flat: {
      'db_bloodline:name': string;
      'db_bloodline:display': string;
      'db_proficiency:name': string;
      'db_proficiency:shortName': string;
      'db_proficiency:displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'BONUS' | 'MAGIE' | 'PACIFICATEURS' | 'PAROLIERS' | 'SOLDATS' | 'SOUTIENS' | 'STATS' | 'TECHNOMANCIE';
      'db_proficiency:description': string;
      'db_proficiency:minLevel': number;
    };
  };
  'db_bloodline_skills_db_skill': {
    plain: {
      'dbBloodlineName': string;
      'dbSkillId': number;
    };
    nested: {
      'db_bloodline': Schema['db_bloodline']['plain'] & Schema['db_bloodline']['nested'];
      'dbSkill': Schema['db_skill']['plain'] & Schema['db_skill']['nested'];
    };
    flat: {
      'db_bloodline:name': string;
      'db_bloodline:display': string;
      'dbSkill:id': number;
      'dbSkill:displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'BONUS' | 'MAGIE' | 'PACIFICATEURS' | 'PAROLIERS' | 'SOLDATS' | 'SOUTIENS' | 'STATS' | 'TECHNOMANCIE';
      'dbSkill:allowsPf': boolean;
      'dbSkill:allowsPp': boolean;
      'dbSkill:stat': 'CHAIR' | 'CUSTOM' | 'EMPIRIQUE' | 'ESPRIT' | 'ESSENCE' | 'FIXE';
      'dbSkill:pvCost': number;
      'dbSkill:pfCost': number;
      'dbSkill:ppCost': number;
      'dbSkill:dettesCost': number;
      'dbSkill:arcaneCost': number;
      'dbSkill:arcanePrimeCost': number;
      'dbSkill:customRolls': string;
      'dbSkill:successCalculation': 'AUCUN' | 'CUSTOM' | 'DIVISE' | 'DIVISE_PLUS_1' | 'DOUBLE' | 'DOUBLE_PLUS_1' | 'SIMPLE' | 'SIMPLE_PLUS_1';
      'dbSkill:secret': boolean;
      'dbSkill:invocationTemplateName': string;
      'dbSkill:name': string;
      'dbSkill:shortName': string;
      'dbSkill:longName': string;
      'dbSkill:allAttribution': boolean;
      'dbSkill:position': number;
      'dbSkill:display': string;
      'dbSkill:isArcanique': boolean;
      'dbSkill:isHeal': boolean;
      'dbSkill:description': string;
      'dbSkill:precision': string;
      'dbSkill:soldatCost': number;
      'dbSkill:resistance': boolean;
      'dbSkill:blessure': boolean;
      'dbSkill:help': boolean;
      'dbSkill:etherCost': number;
      'dbSkill:owner': string;
      'dbSkill:dragonDettesCost': number;
      'dbSkill:db_character_template:name': string;
      'dbSkill:db_character_template:chairValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'dbSkill:db_character_template:chairValueRule': number;
      'dbSkill:db_character_template:espritValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'dbSkill:db_character_template:espritValueRule': number;
      'dbSkill:db_character_template:essenceValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'dbSkill:db_character_template:essenceValueRule': number;
      'dbSkill:db_character_template:pvMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'dbSkill:db_character_template:pvMaxValueRule': number;
      'dbSkill:db_character_template:pfMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'dbSkill:db_character_template:pfMaxValueRule': number;
      'dbSkill:db_character_template:ppMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'dbSkill:db_character_template:ppMaxValueRule': number;
      'dbSkill:db_character_template:picture': string;
      'dbSkill:db_character_template:customData': string;
      'dbSkill:db_character_template:classeName': string;
      'dbSkill:db_character_template:bloodlineName': string;
      'dbSkill:db_character_template:db_classe:name': string;
      'dbSkill:db_character_template:db_classe:displayMale': string;
      'dbSkill:db_character_template:db_classe:displayFemale': string;
      'dbSkill:db_character_template:db_classe:canUsePp': boolean;
      'dbSkill:db_character_template:db_bloodline:name': string;
      'dbSkill:db_character_template:db_bloodline:display': string;
    };
  };
  'db_character': {
    plain: {
      'name': string;
      'classeName': string;
      'controlledBy': string;
      'isInvocation': boolean;
      'currentApotheoseName': string;
      'apotheoseState': 'ALREADY_USED' | 'COST_PAID' | 'COST_TO_PAY' | 'NONE';
      'chair': number;
      'esprit': number;
      'essence': number;
      'pv': number;
      'pvMax': number;
      'pf': number;
      'pfMax': number;
      'pp': number;
      'ppMax': number;
      'dettes': number;
      'arcanes': number;
      'arcanesMax': number;
      'arcanePrimes': number;
      'arcanePrimesMax': number;
      'munitions': number;
      'munitionsMax': number;
      'niveau': number;
      'restImproved': boolean;
      'lux': string;
      'umbra': string;
      'secunda': string;
      'notes': string;
      'battleState': 'ALLIES' | 'ENNEMIES' | 'NONE';
      'genre': 'FEMME' | 'HOMME';
      'relance': number;
      'playerName': string;
      'picture': string;
      'pictureApotheose': string;
      'background': string;
      'buttonColor': string;
      'textColor': string;
      'boosted': boolean;
      'bloodlineName': string;
      'customData': string;
      'dailyUse': any;
      'dailyUseMax': any;
      'ether': number;
      'etherMax': number;
      'hurtMalus': boolean;
      'boulet': boolean;
      'dragonDettes': number;
      'arcaneDette': any;
      'dark': boolean;
    };
    nested: {
      'db_classe': Schema['db_classe']['plain'] & Schema['db_classe']['nested'];
      'db_apotheose': Schema['db_apotheose']['plain'] & Schema['db_apotheose']['nested'];
      'db_bloodline': Schema['db_bloodline']['plain'] & Schema['db_bloodline']['nested'];
    };
    flat: {
      'db_classe:name': string;
      'db_classe:displayMale': string;
      'db_classe:displayFemale': string;
      'db_classe:canUsePp': boolean;
      'db_apotheose:name': string;
      'db_apotheose:shortName': string;
      'db_apotheose:displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'BONUS' | 'MAGIE' | 'PACIFICATEURS' | 'PAROLIERS' | 'SOLDATS' | 'SOUTIENS' | 'STATS' | 'TECHNOMANCIE';
      'db_apotheose:description': string;
      'db_apotheose:position': number;
      'db_apotheose:minLevel': number;
      'db_apotheose:maxLevel': number;
      'db_apotheose:cost': number;
      'db_apotheose:chairImprovement': number;
      'db_apotheose:espritImprovement': number;
      'db_apotheose:essenceImprovement': number;
      'db_apotheose:arcaneImprovement': boolean;
      'db_apotheose:avantage': boolean;
      'db_apotheose:apotheoseEffect': string;
      'db_bloodline:name': string;
      'db_bloodline:display': string;
    };
  };
  'db_character_apotheoses_db_apotheose': {
    plain: {
      'dbCharacterName': string;
      'dbApotheoseName': string;
    };
    nested: {
      'db_character': Schema['db_character']['plain'] & Schema['db_character']['nested'];
      'db_apotheose': Schema['db_apotheose']['plain'] & Schema['db_apotheose']['nested'];
    };
    flat: {
      'db_character:name': string;
      'db_character:classeName': string;
      'db_character:controlledBy': string;
      'db_character:isInvocation': boolean;
      'db_character:currentApotheoseName': string;
      'db_character:apotheoseState': 'ALREADY_USED' | 'COST_PAID' | 'COST_TO_PAY' | 'NONE';
      'db_character:chair': number;
      'db_character:esprit': number;
      'db_character:essence': number;
      'db_character:pv': number;
      'db_character:pvMax': number;
      'db_character:pf': number;
      'db_character:pfMax': number;
      'db_character:pp': number;
      'db_character:ppMax': number;
      'db_character:dettes': number;
      'db_character:arcanes': number;
      'db_character:arcanesMax': number;
      'db_character:arcanePrimes': number;
      'db_character:arcanePrimesMax': number;
      'db_character:munitions': number;
      'db_character:munitionsMax': number;
      'db_character:niveau': number;
      'db_character:restImproved': boolean;
      'db_character:lux': string;
      'db_character:umbra': string;
      'db_character:secunda': string;
      'db_character:notes': string;
      'db_character:battleState': 'ALLIES' | 'ENNEMIES' | 'NONE';
      'db_character:genre': 'FEMME' | 'HOMME';
      'db_character:relance': number;
      'db_character:playerName': string;
      'db_character:picture': string;
      'db_character:pictureApotheose': string;
      'db_character:background': string;
      'db_character:buttonColor': string;
      'db_character:textColor': string;
      'db_character:boosted': boolean;
      'db_character:bloodlineName': string;
      'db_character:customData': string;
      'db_character:dailyUse': any;
      'db_character:dailyUseMax': any;
      'db_character:ether': number;
      'db_character:etherMax': number;
      'db_character:hurtMalus': boolean;
      'db_character:boulet': boolean;
      'db_character:dragonDettes': number;
      'db_character:arcaneDette': any;
      'db_character:dark': boolean;
      'db_character:db_classe:name': string;
      'db_character:db_classe:displayMale': string;
      'db_character:db_classe:displayFemale': string;
      'db_character:db_classe:canUsePp': boolean;
      'db_character:db_apotheose:name': string;
      'db_character:db_apotheose:shortName': string;
      'db_character:db_apotheose:displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'BONUS' | 'MAGIE' | 'PACIFICATEURS' | 'PAROLIERS' | 'SOLDATS' | 'SOUTIENS' | 'STATS' | 'TECHNOMANCIE';
      'db_character:db_apotheose:description': string;
      'db_character:db_apotheose:position': number;
      'db_character:db_apotheose:minLevel': number;
      'db_character:db_apotheose:maxLevel': number;
      'db_character:db_apotheose:cost': number;
      'db_character:db_apotheose:chairImprovement': number;
      'db_character:db_apotheose:espritImprovement': number;
      'db_character:db_apotheose:essenceImprovement': number;
      'db_character:db_apotheose:arcaneImprovement': boolean;
      'db_character:db_apotheose:avantage': boolean;
      'db_character:db_apotheose:apotheoseEffect': string;
      'db_character:db_bloodline:name': string;
      'db_character:db_bloodline:display': string;
      'db_apotheose:name': string;
      'db_apotheose:shortName': string;
      'db_apotheose:displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'BONUS' | 'MAGIE' | 'PACIFICATEURS' | 'PAROLIERS' | 'SOLDATS' | 'SOUTIENS' | 'STATS' | 'TECHNOMANCIE';
      'db_apotheose:description': string;
      'db_apotheose:position': number;
      'db_apotheose:minLevel': number;
      'db_apotheose:maxLevel': number;
      'db_apotheose:cost': number;
      'db_apotheose:chairImprovement': number;
      'db_apotheose:espritImprovement': number;
      'db_apotheose:essenceImprovement': number;
      'db_apotheose:arcaneImprovement': boolean;
      'db_apotheose:avantage': boolean;
      'db_apotheose:apotheoseEffect': string;
    };
  };
  'db_character_proficiencies_db_proficiency': {
    plain: {
      'dbCharacterName': string;
      'dbProficiencyName': string;
    };
    nested: {
      'db_character': Schema['db_character']['plain'] & Schema['db_character']['nested'];
      'db_proficiency': Schema['db_proficiency']['plain'] & Schema['db_proficiency']['nested'];
    };
    flat: {
      'db_character:name': string;
      'db_character:classeName': string;
      'db_character:controlledBy': string;
      'db_character:isInvocation': boolean;
      'db_character:currentApotheoseName': string;
      'db_character:apotheoseState': 'ALREADY_USED' | 'COST_PAID' | 'COST_TO_PAY' | 'NONE';
      'db_character:chair': number;
      'db_character:esprit': number;
      'db_character:essence': number;
      'db_character:pv': number;
      'db_character:pvMax': number;
      'db_character:pf': number;
      'db_character:pfMax': number;
      'db_character:pp': number;
      'db_character:ppMax': number;
      'db_character:dettes': number;
      'db_character:arcanes': number;
      'db_character:arcanesMax': number;
      'db_character:arcanePrimes': number;
      'db_character:arcanePrimesMax': number;
      'db_character:munitions': number;
      'db_character:munitionsMax': number;
      'db_character:niveau': number;
      'db_character:restImproved': boolean;
      'db_character:lux': string;
      'db_character:umbra': string;
      'db_character:secunda': string;
      'db_character:notes': string;
      'db_character:battleState': 'ALLIES' | 'ENNEMIES' | 'NONE';
      'db_character:genre': 'FEMME' | 'HOMME';
      'db_character:relance': number;
      'db_character:playerName': string;
      'db_character:picture': string;
      'db_character:pictureApotheose': string;
      'db_character:background': string;
      'db_character:buttonColor': string;
      'db_character:textColor': string;
      'db_character:boosted': boolean;
      'db_character:bloodlineName': string;
      'db_character:customData': string;
      'db_character:dailyUse': any;
      'db_character:dailyUseMax': any;
      'db_character:ether': number;
      'db_character:etherMax': number;
      'db_character:hurtMalus': boolean;
      'db_character:boulet': boolean;
      'db_character:dragonDettes': number;
      'db_character:arcaneDette': any;
      'db_character:dark': boolean;
      'db_character:db_classe:name': string;
      'db_character:db_classe:displayMale': string;
      'db_character:db_classe:displayFemale': string;
      'db_character:db_classe:canUsePp': boolean;
      'db_character:db_apotheose:name': string;
      'db_character:db_apotheose:shortName': string;
      'db_character:db_apotheose:displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'BONUS' | 'MAGIE' | 'PACIFICATEURS' | 'PAROLIERS' | 'SOLDATS' | 'SOUTIENS' | 'STATS' | 'TECHNOMANCIE';
      'db_character:db_apotheose:description': string;
      'db_character:db_apotheose:position': number;
      'db_character:db_apotheose:minLevel': number;
      'db_character:db_apotheose:maxLevel': number;
      'db_character:db_apotheose:cost': number;
      'db_character:db_apotheose:chairImprovement': number;
      'db_character:db_apotheose:espritImprovement': number;
      'db_character:db_apotheose:essenceImprovement': number;
      'db_character:db_apotheose:arcaneImprovement': boolean;
      'db_character:db_apotheose:avantage': boolean;
      'db_character:db_apotheose:apotheoseEffect': string;
      'db_character:db_bloodline:name': string;
      'db_character:db_bloodline:display': string;
      'db_proficiency:name': string;
      'db_proficiency:shortName': string;
      'db_proficiency:displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'BONUS' | 'MAGIE' | 'PACIFICATEURS' | 'PAROLIERS' | 'SOLDATS' | 'SOUTIENS' | 'STATS' | 'TECHNOMANCIE';
      'db_proficiency:description': string;
      'db_proficiency:minLevel': number;
    };
  };
  'db_character_skills_db_skill': {
    plain: {
      'dbCharacterName': string;
      'dbSkillId': number;
    };
    nested: {
      'db_character': Schema['db_character']['plain'] & Schema['db_character']['nested'];
      'dbSkill': Schema['db_skill']['plain'] & Schema['db_skill']['nested'];
    };
    flat: {
      'db_character:name': string;
      'db_character:classeName': string;
      'db_character:controlledBy': string;
      'db_character:isInvocation': boolean;
      'db_character:currentApotheoseName': string;
      'db_character:apotheoseState': 'ALREADY_USED' | 'COST_PAID' | 'COST_TO_PAY' | 'NONE';
      'db_character:chair': number;
      'db_character:esprit': number;
      'db_character:essence': number;
      'db_character:pv': number;
      'db_character:pvMax': number;
      'db_character:pf': number;
      'db_character:pfMax': number;
      'db_character:pp': number;
      'db_character:ppMax': number;
      'db_character:dettes': number;
      'db_character:arcanes': number;
      'db_character:arcanesMax': number;
      'db_character:arcanePrimes': number;
      'db_character:arcanePrimesMax': number;
      'db_character:munitions': number;
      'db_character:munitionsMax': number;
      'db_character:niveau': number;
      'db_character:restImproved': boolean;
      'db_character:lux': string;
      'db_character:umbra': string;
      'db_character:secunda': string;
      'db_character:notes': string;
      'db_character:battleState': 'ALLIES' | 'ENNEMIES' | 'NONE';
      'db_character:genre': 'FEMME' | 'HOMME';
      'db_character:relance': number;
      'db_character:playerName': string;
      'db_character:picture': string;
      'db_character:pictureApotheose': string;
      'db_character:background': string;
      'db_character:buttonColor': string;
      'db_character:textColor': string;
      'db_character:boosted': boolean;
      'db_character:bloodlineName': string;
      'db_character:customData': string;
      'db_character:dailyUse': any;
      'db_character:dailyUseMax': any;
      'db_character:ether': number;
      'db_character:etherMax': number;
      'db_character:hurtMalus': boolean;
      'db_character:boulet': boolean;
      'db_character:dragonDettes': number;
      'db_character:arcaneDette': any;
      'db_character:dark': boolean;
      'db_character:db_classe:name': string;
      'db_character:db_classe:displayMale': string;
      'db_character:db_classe:displayFemale': string;
      'db_character:db_classe:canUsePp': boolean;
      'db_character:db_apotheose:name': string;
      'db_character:db_apotheose:shortName': string;
      'db_character:db_apotheose:displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'BONUS' | 'MAGIE' | 'PACIFICATEURS' | 'PAROLIERS' | 'SOLDATS' | 'SOUTIENS' | 'STATS' | 'TECHNOMANCIE';
      'db_character:db_apotheose:description': string;
      'db_character:db_apotheose:position': number;
      'db_character:db_apotheose:minLevel': number;
      'db_character:db_apotheose:maxLevel': number;
      'db_character:db_apotheose:cost': number;
      'db_character:db_apotheose:chairImprovement': number;
      'db_character:db_apotheose:espritImprovement': number;
      'db_character:db_apotheose:essenceImprovement': number;
      'db_character:db_apotheose:arcaneImprovement': boolean;
      'db_character:db_apotheose:avantage': boolean;
      'db_character:db_apotheose:apotheoseEffect': string;
      'db_character:db_bloodline:name': string;
      'db_character:db_bloodline:display': string;
      'dbSkill:id': number;
      'dbSkill:displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'BONUS' | 'MAGIE' | 'PACIFICATEURS' | 'PAROLIERS' | 'SOLDATS' | 'SOUTIENS' | 'STATS' | 'TECHNOMANCIE';
      'dbSkill:allowsPf': boolean;
      'dbSkill:allowsPp': boolean;
      'dbSkill:stat': 'CHAIR' | 'CUSTOM' | 'EMPIRIQUE' | 'ESPRIT' | 'ESSENCE' | 'FIXE';
      'dbSkill:pvCost': number;
      'dbSkill:pfCost': number;
      'dbSkill:ppCost': number;
      'dbSkill:dettesCost': number;
      'dbSkill:arcaneCost': number;
      'dbSkill:arcanePrimeCost': number;
      'dbSkill:customRolls': string;
      'dbSkill:successCalculation': 'AUCUN' | 'CUSTOM' | 'DIVISE' | 'DIVISE_PLUS_1' | 'DOUBLE' | 'DOUBLE_PLUS_1' | 'SIMPLE' | 'SIMPLE_PLUS_1';
      'dbSkill:secret': boolean;
      'dbSkill:invocationTemplateName': string;
      'dbSkill:name': string;
      'dbSkill:shortName': string;
      'dbSkill:longName': string;
      'dbSkill:allAttribution': boolean;
      'dbSkill:position': number;
      'dbSkill:display': string;
      'dbSkill:isArcanique': boolean;
      'dbSkill:isHeal': boolean;
      'dbSkill:description': string;
      'dbSkill:precision': string;
      'dbSkill:soldatCost': number;
      'dbSkill:resistance': boolean;
      'dbSkill:blessure': boolean;
      'dbSkill:help': boolean;
      'dbSkill:etherCost': number;
      'dbSkill:owner': string;
      'dbSkill:dragonDettesCost': number;
      'dbSkill:db_character_template:name': string;
      'dbSkill:db_character_template:chairValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'dbSkill:db_character_template:chairValueRule': number;
      'dbSkill:db_character_template:espritValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'dbSkill:db_character_template:espritValueRule': number;
      'dbSkill:db_character_template:essenceValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'dbSkill:db_character_template:essenceValueRule': number;
      'dbSkill:db_character_template:pvMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'dbSkill:db_character_template:pvMaxValueRule': number;
      'dbSkill:db_character_template:pfMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'dbSkill:db_character_template:pfMaxValueRule': number;
      'dbSkill:db_character_template:ppMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'dbSkill:db_character_template:ppMaxValueRule': number;
      'dbSkill:db_character_template:picture': string;
      'dbSkill:db_character_template:customData': string;
      'dbSkill:db_character_template:classeName': string;
      'dbSkill:db_character_template:bloodlineName': string;
      'dbSkill:db_character_template:db_classe:name': string;
      'dbSkill:db_character_template:db_classe:displayMale': string;
      'dbSkill:db_character_template:db_classe:displayFemale': string;
      'dbSkill:db_character_template:db_classe:canUsePp': boolean;
      'dbSkill:db_character_template:db_bloodline:name': string;
      'dbSkill:db_character_template:db_bloodline:display': string;
    };
  };
  'db_character_template': {
    plain: {
      'name': string;
      'chairValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'chairValueRule': number;
      'espritValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'espritValueRule': number;
      'essenceValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'essenceValueRule': number;
      'pvMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'pvMaxValueRule': number;
      'pfMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'pfMaxValueRule': number;
      'ppMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'ppMaxValueRule': number;
      'picture': string;
      'customData': string;
      'classeName': string;
      'bloodlineName': string;
    };
    nested: {
      'db_classe': Schema['db_classe']['plain'] & Schema['db_classe']['nested'];
      'db_bloodline': Schema['db_bloodline']['plain'] & Schema['db_bloodline']['nested'];
    };
    flat: {
      'db_classe:name': string;
      'db_classe:displayMale': string;
      'db_classe:displayFemale': string;
      'db_classe:canUsePp': boolean;
      'db_bloodline:name': string;
      'db_bloodline:display': string;
    };
  };
  'db_character_template_skills_db_skill': {
    plain: {
      'dbCharacterTemplateName': string;
      'dbSkillId': number;
    };
    nested: {
      'db_character_template': Schema['db_character_template']['plain'] & Schema['db_character_template']['nested'];
      'dbSkill': Schema['db_skill']['plain'] & Schema['db_skill']['nested'];
    };
    flat: {
      'db_character_template:name': string;
      'db_character_template:chairValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:chairValueRule': number;
      'db_character_template:espritValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:espritValueRule': number;
      'db_character_template:essenceValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:essenceValueRule': number;
      'db_character_template:pvMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:pvMaxValueRule': number;
      'db_character_template:pfMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:pfMaxValueRule': number;
      'db_character_template:ppMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:ppMaxValueRule': number;
      'db_character_template:picture': string;
      'db_character_template:customData': string;
      'db_character_template:classeName': string;
      'db_character_template:bloodlineName': string;
      'db_character_template:db_classe:name': string;
      'db_character_template:db_classe:displayMale': string;
      'db_character_template:db_classe:displayFemale': string;
      'db_character_template:db_classe:canUsePp': boolean;
      'db_character_template:db_bloodline:name': string;
      'db_character_template:db_bloodline:display': string;
      'dbSkill:id': number;
      'dbSkill:displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'BONUS' | 'MAGIE' | 'PACIFICATEURS' | 'PAROLIERS' | 'SOLDATS' | 'SOUTIENS' | 'STATS' | 'TECHNOMANCIE';
      'dbSkill:allowsPf': boolean;
      'dbSkill:allowsPp': boolean;
      'dbSkill:stat': 'CHAIR' | 'CUSTOM' | 'EMPIRIQUE' | 'ESPRIT' | 'ESSENCE' | 'FIXE';
      'dbSkill:pvCost': number;
      'dbSkill:pfCost': number;
      'dbSkill:ppCost': number;
      'dbSkill:dettesCost': number;
      'dbSkill:arcaneCost': number;
      'dbSkill:arcanePrimeCost': number;
      'dbSkill:customRolls': string;
      'dbSkill:successCalculation': 'AUCUN' | 'CUSTOM' | 'DIVISE' | 'DIVISE_PLUS_1' | 'DOUBLE' | 'DOUBLE_PLUS_1' | 'SIMPLE' | 'SIMPLE_PLUS_1';
      'dbSkill:secret': boolean;
      'dbSkill:invocationTemplateName': string;
      'dbSkill:name': string;
      'dbSkill:shortName': string;
      'dbSkill:longName': string;
      'dbSkill:allAttribution': boolean;
      'dbSkill:position': number;
      'dbSkill:display': string;
      'dbSkill:isArcanique': boolean;
      'dbSkill:isHeal': boolean;
      'dbSkill:description': string;
      'dbSkill:precision': string;
      'dbSkill:soldatCost': number;
      'dbSkill:resistance': boolean;
      'dbSkill:blessure': boolean;
      'dbSkill:help': boolean;
      'dbSkill:etherCost': number;
      'dbSkill:owner': string;
      'dbSkill:dragonDettesCost': number;
      'dbSkill:db_character_template:name': string;
      'dbSkill:db_character_template:chairValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'dbSkill:db_character_template:chairValueRule': number;
      'dbSkill:db_character_template:espritValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'dbSkill:db_character_template:espritValueRule': number;
      'dbSkill:db_character_template:essenceValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'dbSkill:db_character_template:essenceValueRule': number;
      'dbSkill:db_character_template:pvMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'dbSkill:db_character_template:pvMaxValueRule': number;
      'dbSkill:db_character_template:pfMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'dbSkill:db_character_template:pfMaxValueRule': number;
      'dbSkill:db_character_template:ppMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'dbSkill:db_character_template:ppMaxValueRule': number;
      'dbSkill:db_character_template:picture': string;
      'dbSkill:db_character_template:customData': string;
      'dbSkill:db_character_template:classeName': string;
      'dbSkill:db_character_template:bloodlineName': string;
      'dbSkill:db_character_template:db_classe:name': string;
      'dbSkill:db_character_template:db_classe:displayMale': string;
      'dbSkill:db_character_template:db_classe:displayFemale': string;
      'dbSkill:db_character_template:db_classe:canUsePp': boolean;
      'dbSkill:db_character_template:db_bloodline:name': string;
      'dbSkill:db_character_template:db_bloodline:display': string;
    };
  };
  'db_classe': {
    plain: {
      'name': string;
      'displayMale': string;
      'displayFemale': string;
      'canUsePp': boolean;
    };
    nested: {};
    flat: {};
  };
  'db_classe_apotheoses_db_apotheose': {
    plain: {
      'dbClasseName': string;
      'dbApotheoseName': string;
    };
    nested: {
      'db_classe': Schema['db_classe']['plain'] & Schema['db_classe']['nested'];
      'db_apotheose': Schema['db_apotheose']['plain'] & Schema['db_apotheose']['nested'];
    };
    flat: {
      'db_classe:name': string;
      'db_classe:displayMale': string;
      'db_classe:displayFemale': string;
      'db_classe:canUsePp': boolean;
      'db_apotheose:name': string;
      'db_apotheose:shortName': string;
      'db_apotheose:displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'BONUS' | 'MAGIE' | 'PACIFICATEURS' | 'PAROLIERS' | 'SOLDATS' | 'SOUTIENS' | 'STATS' | 'TECHNOMANCIE';
      'db_apotheose:description': string;
      'db_apotheose:position': number;
      'db_apotheose:minLevel': number;
      'db_apotheose:maxLevel': number;
      'db_apotheose:cost': number;
      'db_apotheose:chairImprovement': number;
      'db_apotheose:espritImprovement': number;
      'db_apotheose:essenceImprovement': number;
      'db_apotheose:arcaneImprovement': boolean;
      'db_apotheose:avantage': boolean;
      'db_apotheose:apotheoseEffect': string;
    };
  };
  'db_classe_proficiencies_db_proficiency': {
    plain: {
      'dbClasseName': string;
      'dbProficiencyName': string;
    };
    nested: {
      'db_classe': Schema['db_classe']['plain'] & Schema['db_classe']['nested'];
      'db_proficiency': Schema['db_proficiency']['plain'] & Schema['db_proficiency']['nested'];
    };
    flat: {
      'db_classe:name': string;
      'db_classe:displayMale': string;
      'db_classe:displayFemale': string;
      'db_classe:canUsePp': boolean;
      'db_proficiency:name': string;
      'db_proficiency:shortName': string;
      'db_proficiency:displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'BONUS' | 'MAGIE' | 'PACIFICATEURS' | 'PAROLIERS' | 'SOLDATS' | 'SOUTIENS' | 'STATS' | 'TECHNOMANCIE';
      'db_proficiency:description': string;
      'db_proficiency:minLevel': number;
    };
  };
  'db_classe_skills_db_skill': {
    plain: {
      'dbClasseName': string;
      'dbSkillId': number;
    };
    nested: {
      'db_classe': Schema['db_classe']['plain'] & Schema['db_classe']['nested'];
      'dbSkill': Schema['db_skill']['plain'] & Schema['db_skill']['nested'];
    };
    flat: {
      'db_classe:name': string;
      'db_classe:displayMale': string;
      'db_classe:displayFemale': string;
      'db_classe:canUsePp': boolean;
      'dbSkill:id': number;
      'dbSkill:displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'BONUS' | 'MAGIE' | 'PACIFICATEURS' | 'PAROLIERS' | 'SOLDATS' | 'SOUTIENS' | 'STATS' | 'TECHNOMANCIE';
      'dbSkill:allowsPf': boolean;
      'dbSkill:allowsPp': boolean;
      'dbSkill:stat': 'CHAIR' | 'CUSTOM' | 'EMPIRIQUE' | 'ESPRIT' | 'ESSENCE' | 'FIXE';
      'dbSkill:pvCost': number;
      'dbSkill:pfCost': number;
      'dbSkill:ppCost': number;
      'dbSkill:dettesCost': number;
      'dbSkill:arcaneCost': number;
      'dbSkill:arcanePrimeCost': number;
      'dbSkill:customRolls': string;
      'dbSkill:successCalculation': 'AUCUN' | 'CUSTOM' | 'DIVISE' | 'DIVISE_PLUS_1' | 'DOUBLE' | 'DOUBLE_PLUS_1' | 'SIMPLE' | 'SIMPLE_PLUS_1';
      'dbSkill:secret': boolean;
      'dbSkill:invocationTemplateName': string;
      'dbSkill:name': string;
      'dbSkill:shortName': string;
      'dbSkill:longName': string;
      'dbSkill:allAttribution': boolean;
      'dbSkill:position': number;
      'dbSkill:display': string;
      'dbSkill:isArcanique': boolean;
      'dbSkill:isHeal': boolean;
      'dbSkill:description': string;
      'dbSkill:precision': string;
      'dbSkill:soldatCost': number;
      'dbSkill:resistance': boolean;
      'dbSkill:blessure': boolean;
      'dbSkill:help': boolean;
      'dbSkill:etherCost': number;
      'dbSkill:owner': string;
      'dbSkill:dragonDettesCost': number;
      'dbSkill:db_character_template:name': string;
      'dbSkill:db_character_template:chairValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'dbSkill:db_character_template:chairValueRule': number;
      'dbSkill:db_character_template:espritValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'dbSkill:db_character_template:espritValueRule': number;
      'dbSkill:db_character_template:essenceValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'dbSkill:db_character_template:essenceValueRule': number;
      'dbSkill:db_character_template:pvMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'dbSkill:db_character_template:pvMaxValueRule': number;
      'dbSkill:db_character_template:pfMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'dbSkill:db_character_template:pfMaxValueRule': number;
      'dbSkill:db_character_template:ppMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'dbSkill:db_character_template:ppMaxValueRule': number;
      'dbSkill:db_character_template:picture': string;
      'dbSkill:db_character_template:customData': string;
      'dbSkill:db_character_template:classeName': string;
      'dbSkill:db_character_template:bloodlineName': string;
      'dbSkill:db_character_template:db_classe:name': string;
      'dbSkill:db_character_template:db_classe:displayMale': string;
      'dbSkill:db_character_template:db_classe:displayFemale': string;
      'dbSkill:db_character_template:db_classe:canUsePp': boolean;
      'dbSkill:db_character_template:db_bloodline:name': string;
      'dbSkill:db_character_template:db_bloodline:display': string;
    };
  };
  'db_entry': {
    plain: {
      'day': number;
      'month': number;
      'year': number;
      'text': string;
    };
    nested: {};
    flat: {};
  };
  'db_knowledge': {
    plain: {
      'id': string;
      'createdDate': string;
      'updatedDate': string;
      'name': string;
      'statId': string;
    };
    nested: {
      'stat': Schema['db_stat']['plain'] & Schema['db_stat']['nested'];
    };
    flat: {
      'stat:id': string;
      'stat:createdDate': string;
      'stat:updatedDate': string;
      'stat:name': string;
      'stat:color': string;
    };
  };
  'db_proficiency': {
    plain: {
      'name': string;
      'shortName': string;
      'displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'BONUS' | 'MAGIE' | 'PACIFICATEURS' | 'PAROLIERS' | 'SOLDATS' | 'SOUTIENS' | 'STATS' | 'TECHNOMANCIE';
      'description': string;
      'minLevel': number;
    };
    nested: {};
    flat: {};
  };
  'db_roll': {
    plain: {
      'rollerName': string;
      'date': string;
      'stat': 'CHAIR' | 'CUSTOM' | 'EMPIRIQUE' | 'ESPRIT' | 'ESSENCE' | 'FIXE';
      'secret': boolean;
      'focus': boolean;
      'power': boolean;
      'proficiency': boolean;
      'bonus': number;
      'malus': number;
      'result': string;
      'success': number;
      'juge12': number;
      'juge34': number;
      'picture': string;
      'illustration': string;
      'data': string;
      'empiriqueRoll': string;
      'resistRoll': string;
      'display': string;
      'healPoint': number;
      'displayDices': boolean;
      'id': string;
      'resistance': boolean;
      'blessure': boolean;
      'help': boolean;
      'precision': string;
      'pictureUrl': string;
      'dark': boolean;
    };
    nested: {
      'db_character': Schema['db_character']['plain'] & Schema['db_character']['nested'];
    };
    flat: {
      'db_character:name': string;
      'db_character:classeName': string;
      'db_character:controlledBy': string;
      'db_character:isInvocation': boolean;
      'db_character:currentApotheoseName': string;
      'db_character:apotheoseState': 'ALREADY_USED' | 'COST_PAID' | 'COST_TO_PAY' | 'NONE';
      'db_character:chair': number;
      'db_character:esprit': number;
      'db_character:essence': number;
      'db_character:pv': number;
      'db_character:pvMax': number;
      'db_character:pf': number;
      'db_character:pfMax': number;
      'db_character:pp': number;
      'db_character:ppMax': number;
      'db_character:dettes': number;
      'db_character:arcanes': number;
      'db_character:arcanesMax': number;
      'db_character:arcanePrimes': number;
      'db_character:arcanePrimesMax': number;
      'db_character:munitions': number;
      'db_character:munitionsMax': number;
      'db_character:niveau': number;
      'db_character:restImproved': boolean;
      'db_character:lux': string;
      'db_character:umbra': string;
      'db_character:secunda': string;
      'db_character:notes': string;
      'db_character:battleState': 'ALLIES' | 'ENNEMIES' | 'NONE';
      'db_character:genre': 'FEMME' | 'HOMME';
      'db_character:relance': number;
      'db_character:playerName': string;
      'db_character:picture': string;
      'db_character:pictureApotheose': string;
      'db_character:background': string;
      'db_character:buttonColor': string;
      'db_character:textColor': string;
      'db_character:boosted': boolean;
      'db_character:bloodlineName': string;
      'db_character:customData': string;
      'db_character:dailyUse': any;
      'db_character:dailyUseMax': any;
      'db_character:ether': number;
      'db_character:etherMax': number;
      'db_character:hurtMalus': boolean;
      'db_character:boulet': boolean;
      'db_character:dragonDettes': number;
      'db_character:arcaneDette': any;
      'db_character:dark': boolean;
      'db_character:db_classe:name': string;
      'db_character:db_classe:displayMale': string;
      'db_character:db_classe:displayFemale': string;
      'db_character:db_classe:canUsePp': boolean;
      'db_character:db_apotheose:name': string;
      'db_character:db_apotheose:shortName': string;
      'db_character:db_apotheose:displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'BONUS' | 'MAGIE' | 'PACIFICATEURS' | 'PAROLIERS' | 'SOLDATS' | 'SOUTIENS' | 'STATS' | 'TECHNOMANCIE';
      'db_character:db_apotheose:description': string;
      'db_character:db_apotheose:position': number;
      'db_character:db_apotheose:minLevel': number;
      'db_character:db_apotheose:maxLevel': number;
      'db_character:db_apotheose:cost': number;
      'db_character:db_apotheose:chairImprovement': number;
      'db_character:db_apotheose:espritImprovement': number;
      'db_character:db_apotheose:essenceImprovement': number;
      'db_character:db_apotheose:arcaneImprovement': boolean;
      'db_character:db_apotheose:avantage': boolean;
      'db_character:db_apotheose:apotheoseEffect': string;
      'db_character:db_bloodline:name': string;
      'db_character:db_bloodline:display': string;
    };
  };
  'db_session': {
    plain: {
      'id': number;
      'chaos': '0' | '15' | '30' | '45' | '60' | '75';
      'nature': 'LEVEL_0_PAUVRE' | 'LEVEL_1_RARE' | 'LEVEL_2_PRESENTE' | 'LEVEL_3_ABONDANTE' | 'LEVEL_4_RICHE' | 'LEVEL_5_DOMINANTE';
      'baseRest': number;
      'improvedRest': number;
      'owners': string;
      'fake': number;
      'entries': string;
      'speaking': string;
    };
    nested: {};
    flat: {};
  };
  'db_skill': {
    plain: {
      'id': number;
      'displayCategory': 'ARCANES' | 'ARCANES_PRIMES' | 'BONUS' | 'MAGIE' | 'PACIFICATEURS' | 'PAROLIERS' | 'SOLDATS' | 'SOUTIENS' | 'STATS' | 'TECHNOMANCIE';
      'allowsPf': boolean;
      'allowsPp': boolean;
      'stat': 'CHAIR' | 'CUSTOM' | 'EMPIRIQUE' | 'ESPRIT' | 'ESSENCE' | 'FIXE';
      'pvCost': number;
      'pfCost': number;
      'ppCost': number;
      'dettesCost': number;
      'arcaneCost': number;
      'arcanePrimeCost': number;
      'customRolls': string;
      'successCalculation': 'AUCUN' | 'CUSTOM' | 'DIVISE' | 'DIVISE_PLUS_1' | 'DOUBLE' | 'DOUBLE_PLUS_1' | 'SIMPLE' | 'SIMPLE_PLUS_1';
      'secret': boolean;
      'invocationTemplateName': string;
      'name': string;
      'shortName': string;
      'longName': string;
      'allAttribution': boolean;
      'position': number;
      'display': string;
      'isArcanique': boolean;
      'isHeal': boolean;
      'description': string;
      'precision': string;
      'soldatCost': number;
      'resistance': boolean;
      'blessure': boolean;
      'help': boolean;
      'etherCost': number;
      'owner': string;
      'dragonDettesCost': number;
    };
    nested: {
      'db_character_template': Schema['db_character_template']['plain'] & Schema['db_character_template']['nested'];
    };
    flat: {
      'db_character_template:name': string;
      'db_character_template:chairValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:chairValueRule': number;
      'db_character_template:espritValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:espritValueRule': number;
      'db_character_template:essenceValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:essenceValueRule': number;
      'db_character_template:pvMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:pvMaxValueRule': number;
      'db_character_template:pfMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:pfMaxValueRule': number;
      'db_character_template:ppMaxValueReferential': 'CHAIR' | 'ESPRIT' | 'ESSENCE' | 'FIXE' | 'SUCCESS';
      'db_character_template:ppMaxValueRule': number;
      'db_character_template:picture': string;
      'db_character_template:customData': string;
      'db_character_template:classeName': string;
      'db_character_template:bloodlineName': string;
      'db_character_template:db_classe:name': string;
      'db_character_template:db_classe:displayMale': string;
      'db_character_template:db_classe:displayFemale': string;
      'db_character_template:db_classe:canUsePp': boolean;
      'db_character_template:db_bloodline:name': string;
      'db_character_template:db_bloodline:display': string;
    };
  };
  'db_stat': {
    plain: {
      'id': string;
      'createdDate': string;
      'updatedDate': string;
      'name': string;
      'color': string;
    };
    nested: {};
    flat: {};
  };
  'db_wizard': {
    plain: {
      'id': string;
      'createdDate': string;
      'updatedDate': string;
      'name': string;
      'category': string;
    };
    nested: {};
    flat: {};
  };
  'db_wizard_knowledge': {
    plain: {
      'createdDate': string;
      'updatedDate': string;
      'level': number;
      'wizardId': string;
      'knowledgeId': string;
    };
    nested: {
      'wizard': Schema['db_wizard']['plain'] & Schema['db_wizard']['nested'];
      'knowledge': Schema['db_knowledge']['plain'] & Schema['db_knowledge']['nested'];
    };
    flat: {
      'wizard:id': string;
      'wizard:createdDate': string;
      'wizard:updatedDate': string;
      'wizard:name': string;
      'wizard:category': string;
      'knowledge:id': string;
      'knowledge:createdDate': string;
      'knowledge:updatedDate': string;
      'knowledge:name': string;
      'knowledge:statId': string;
      'knowledge:stat:id': string;
      'knowledge:stat:createdDate': string;
      'knowledge:stat:updatedDate': string;
      'knowledge:stat:name': string;
      'knowledge:stat:color': string;
    };
  };
  'db_wizard_stat': {
    plain: {
      'createdDate': string;
      'updatedDate': string;
      'level': number;
      'wizardId': string;
      'statId': string;
    };
    nested: {
      'wizard': Schema['db_wizard']['plain'] & Schema['db_wizard']['nested'];
      'stat': Schema['db_stat']['plain'] & Schema['db_stat']['nested'];
    };
    flat: {
      'wizard:id': string;
      'wizard:createdDate': string;
      'wizard:updatedDate': string;
      'wizard:name': string;
      'wizard:category': string;
      'stat:id': string;
      'stat:createdDate': string;
      'stat:updatedDate': string;
      'stat:name': string;
      'stat:color': string;
    };
  };
  'Event': {
    plain: {
      'id': string;
      'description': string;
    };
    nested: {};
    flat: {};
  };
  'Joueuse': {
    plain: {
      'id': string;
      'name': string;
      'coins': number;
      'sponsorId': string;
      'scenarioId': string;
      'state': 'FINISHED' | 'NOT_STARTED' | 'STARTED';
      'sponsorToChoose': boolean;
    };
    nested: {
      'sponsor': Schema['Constellation']['plain'] & Schema['Constellation']['nested'];
      'scenario': Schema['Scenario']['plain'] & Schema['Scenario']['nested'];
    };
    flat: {
      'sponsor:id': string;
      'sponsor:name': string;
      'sponsor:pictureUrl': string;
      'sponsor:pictureUrlRevealed': string;
      'sponsor:revealed': boolean;
      'sponsor:realName': string;
      'sponsor:isStarStream': boolean;
      'sponsor:sponsor': boolean;
      'scenario:id': string;
      'scenario:name': string;
      'scenario:difficulty': string;
      'scenario:victory': string;
      'scenario:defeat': string;
      'scenario:time': string;
      'scenario:reward': string;
      'scenario:text': string;
      'scenario:victoryMsg': string;
      'scenario:defaiteMsg': string;
      'scenario:rewardCoin': number;
    };
  };
  'Message': {
    plain: {
      'id': string;
      'text': string;
      'senderId': string;
    };
    nested: {
      'sender': Schema['Constellation']['plain'] & Schema['Constellation']['nested'];
    };
    flat: {
      'sender:id': string;
      'sender:name': string;
      'sender:pictureUrl': string;
      'sender:pictureUrlRevealed': string;
      'sender:revealed': boolean;
      'sender:realName': string;
      'sender:isStarStream': boolean;
      'sender:sponsor': boolean;
    };
  };
  'migrations': {
    plain: {
      'id': number;
      'timestamp': number;
      'name': string;
    };
    nested: {};
    flat: {};
  };
  'ModelMessage': {
    plain: {
      'id': string;
      'text': string;
      'senderId': string;
      'eventId': string;
      'scenarioId': string;
      'scenario': string;
    };
    nested: {
      'sender': Schema['Constellation']['plain'] & Schema['Constellation']['nested'];
      'event': Schema['Event']['plain'] & Schema['Event']['nested'];
      'Scenario': Schema['Scenario']['plain'] & Schema['Scenario']['nested'];
    };
    flat: {
      'sender:id': string;
      'sender:name': string;
      'sender:pictureUrl': string;
      'sender:pictureUrlRevealed': string;
      'sender:revealed': boolean;
      'sender:realName': string;
      'sender:isStarStream': boolean;
      'sender:sponsor': boolean;
      'event:id': string;
      'event:description': string;
      'Scenario:id': string;
      'Scenario:name': string;
      'Scenario:difficulty': string;
      'Scenario:victory': string;
      'Scenario:defeat': string;
      'Scenario:time': string;
      'Scenario:reward': string;
      'Scenario:text': string;
      'Scenario:victoryMsg': string;
      'Scenario:defaiteMsg': string;
      'Scenario:rewardCoin': number;
    };
  };
  'Scenario': {
    plain: {
      'id': string;
      'name': string;
      'difficulty': string;
      'victory': string;
      'defeat': string;
      'time': string;
      'reward': string;
      'text': string;
      'victoryMsg': string;
      'defaiteMsg': string;
      'rewardCoin': number;
    };
    nested: {};
    flat: {};
  };
};
