server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = /healthz {
    access_log off;
    add_header Content-Type text/plain;
    return 200 "ok\n";
  }

  location /recalbox/api/ {
    proxy_pass http://api-recalbox:3335/api/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location = /recalbox {
    try_files /recalbox/index.html =404;
  }

  location /recalbox/ {
    try_files $uri $uri/ /recalbox/index.html;
  }
}
