export enum NatureLevel {
  LEVEL_0_PAUVRE = 'LEVEL_0_PAUVRE',
  LEVEL_1_RARE = 'LEVEL_1_RARE',
  LEVEL_2_PRESENTE = 'LEVEL_2_PRESENTE',
  LEVEL_3_ABONDANTE = 'LEVEL_3_ABONDANTE',
  LEVEL_4_SAUVAGE = 'LEVEL_4_RICHE',
  LEVEL_5_DOMINANTE = 'LEVEL_5_DOMINANTE'
}
