"use client";

import {ChangeEvent,useEffect,useMemo,useState} from "react";

type DateAR={debut_ar:number|null;fin_ar:number|null;texte:string};
type Evenement={id:string;nom:string;date:DateAR;type:string;description:string;importance:string;regions:string[];lieux:string[];factions:string[];personnages:string[];consequences:string[];tags:string[];statut:string;notes?:string;source?:string};
type RefItem={id:string;nom:string};
type Draft={nom:string;debut_ar:string;fin_ar:string;date_texte:string;type:string;description:string;importance:string;regions:string;lieux:string;factions:string;personnages:string;consequences:string;tags:string;statut:string;notes:string;source:string};
const emptyDraft:Draft={nom:"",debut_ar:"",fin_ar:"",date_texte:"",type:"Événement",description:"",importance:"Majeure",regions:"",lieux:"",factions:"",personnages:"",consequences:"",tags:"",statut:"Passé",notes:"",source:""};
const jsonTemplate:Evenement={id:"event_exemple",nom:"Événement exemple",date:{debut_ar:4720,fin_ar:4720,texte:"4720 AR"},type:"Événement",description:"Description courte.",importance:"Majeure",regions:[],lieux:[],factions:[],personnages:[],consequences:[],tags:[],statut:"Passé",notes:"",source:""};
const csv=(v:string)=>[...new Set(v.split(",").map(x=>x.trim()).filter(Boolean))];
const slugId=(v:string)=>"event_"+v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"");
const normalize=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const unique=(v:string[])=>[...new Set(v.filter(Boolean))].sort((a,b)=>a.localeCompare(b,"fr"));
function isEvent(v:unknown):v is Evenement{if(!v||typeof v!=="object")return false;const x=v as Partial<Evenement>;return typeof x.nom==="string"&&typeof x.description==="string"&&!!x.date&&Array.isArray(x.regions)&&Array.isArray(x.tags)}
const downloadJson=(filename:string,data:unknown)=>{const blob=new Blob([JSON.stringify(data,null,2)+"\n"],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url)};
const numberOrNull=(v:string)=>v.trim()===""?null:Number(v);

export default function EvenementsPage({initialSelectedId}:{initialSelectedId?:string}){
  const [items,setItems]=useState<Evenement[]>([]),[pnjs,setPnjs]=useState<RefItem[]>([]),[factions,setFactions]=useState<RefItem[]>([]),[regions,setRegions]=useState<RefItem[]>([]),[lieux,setLieux]=useState<RefItem[]>([]);
  const [query,setQuery]=useState(""),[type,setType]=useState(""),[statut,setStatut]=useState(""),[region,setRegion]=useState("");
  const [selected,setSelected]=useState<Evenement|null>(null),[showAdd,setShowAdd]=useState(false),[draft,setDraft]=useState<Draft>(emptyDraft),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const get=async(url:string)=>{try{const r=await fetch(url,{cache:"no-store"});if(!r.ok)return[];const p=await r.json();return Array.isArray(p)?p:p.items??[]}catch{return[]}};
  const load=async()=>{const r=await fetch("/apil7r/pf2-mj/evenements",{cache:"no-store"});if(!r.ok)throw new Error("Impossible de charger les événements.");const p=await r.json();setItems(Array.isArray(p)?p:p.items??[]);const [a,b,c,d]=await Promise.all([get("/apil7r/pf2-mj/pnj"),get("/apil7r/pf2-mj/factions"),get("/apil7r/pf2-mj/regions"),get("/apil7r/pf2-mj/lieux")]);setPnjs(a);setFactions(b);setRegions(c);setLieux(d)};
  useEffect(()=>{load().catch(e=>setMessage(e instanceof Error?e.message:String(e)))},[]);
  useEffect(()=>{if(initialSelectedId){const target=items.find(item=>item.id===initialSelectedId);if(target)setSelected(target)}},[initialSelectedId,items]);
  const maps=useMemo(()=>({pnjs:new Map(pnjs.map(x=>[x.id,x.nom])),factions:new Map(factions.map(x=>[x.id,x.nom])),regions:new Map(regions.map(x=>[x.id,x.nom])),lieux:new Map(lieux.map(x=>[x.id,x.nom]))}),[pnjs,factions,regions,lieux]);
  const name=(k:keyof typeof maps,id:string)=>maps[k].get(id)??id;
  const types=useMemo(()=>unique(items.map(x=>x.type)),[items]),statuts=useMemo(()=>unique(items.map(x=>x.statut)),[items]);
  const filtered=useMemo(()=>{const q=normalize(query.trim());return items.filter(x=>{const h=normalize([x.nom,x.type,x.description,x.date?.texte,x.source,...x.tags,...x.consequences].filter(Boolean).join(" "));return(!q||h.includes(q))&&(!type||x.type===type)&&(!statut||x.statut===statut)&&(!region||x.regions.includes(region))}).sort((a,b)=>(b.date?.debut_ar??-99999)-(a.date?.debut_ar??-99999)||a.nom.localeCompare(b.nom,"fr"))},[items,query,type,statut,region]);
  const save=async()=>{if(!draft.nom.trim()){setMessage("Le nom est obligatoire.");return}setBusy(true);try{const d0=numberOrNull(draft.debut_ar),d1=numberOrNull(draft.fin_ar);const item:Evenement={id:slugId(draft.nom),nom:draft.nom.trim(),date:{debut_ar:Number.isFinite(d0 as number)?d0:null,fin_ar:Number.isFinite(d1 as number)?d1:null,texte:draft.date_texte.trim()},type:draft.type||"Événement",description:draft.description.trim(),importance:draft.importance||"Majeure",regions:csv(draft.regions),lieux:csv(draft.lieux),factions:csv(draft.factions),personnages:csv(draft.personnages),consequences:csv(draft.consequences),tags:csv(draft.tags),statut:draft.statut||"Passé",notes:draft.notes.trim(),source:draft.source.trim()};
    const r=await fetch("/apil7r/pf2-mj/evenements",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"upsert",item})});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.error||`Erreur HTTP ${r.status}`);setItems(p.items);setDraft(emptyDraft);setShowAdd(false);setSelected(item);setMessage(`${item.nom} enregistré.`)
  }catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
  const importJson=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value="";if(!file)return;setBusy(true);try{const parsed=JSON.parse(await file.text()),raw=Array.isArray(parsed)?parsed:Array.isArray(parsed?.items)?parsed.items:[parsed];const imported:Evenement[]=raw.map((x:any)=>({...x,id:x.id||slugId(x.nom||""),date:x.date??{debut_ar:null,fin_ar:null,texte:""},description:x.description||"",regions:Array.isArray(x.regions)?x.regions:[],lieux:Array.isArray(x.lieux)?x.lieux:[],factions:Array.isArray(x.factions)?x.factions:[],personnages:Array.isArray(x.personnages)?x.personnages:[],consequences:Array.isArray(x.consequences)?x.consequences:[],tags:Array.isArray(x.tags)?x.tags:[]}));if(imported.some(x=>!isEvent(x)))throw new Error("Le JSON contient au moins un événement invalide.");const r=await fetch("/apil7r/pf2-mj/evenements",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"import",items:imported})});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.error||`Erreur HTTP ${r.status}`);setItems(p.items);setMessage(`${imported.length} événement${imported.length>1?"s":""} importé${imported.length>1?"s":""}.`)}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};

  return <main className="ep"><style>{`.ep{max-width:1500px;margin:auto;padding:24px;color:#252a25}.bar{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.bar h1{margin-right:auto}.btn,.file{border:1px solid #c9b98f;background:#fffaf0;color:#6e5319;border-radius:8px;padding:9px 12px;font-weight:700;cursor:pointer}.btn.primary{background:#765719;color:white}.file input{display:none}.msg{min-height:24px;font-size:13px;color:#5d614f}.filters{display:grid;grid-template-columns:2fr repeat(3,1fr);gap:9px;margin:10px 0 18px}.filters input,.filters select,.form input,.form textarea,.form select{width:100%;box-sizing:border-box;border:1px solid #d6cdbd;border-radius:8px;background:#fffdf8;padding:9px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:14px}.card{border:1px solid #ded7cb;background:#fffdf9;border-radius:12px;overflow:hidden}.body{padding:13px}.card h2{margin:0 0 5px;font-size:17px}.date{font-weight:800;color:#765719}.meta{font-size:12px;color:#777}.desc{font-size:13px;line-height:1.45}.more{width:100%;border:0;border-top:1px solid #eee7da;background:#faf7f0;padding:8px;font-weight:700;color:#66542b;cursor:pointer}.back{position:fixed;inset:0;background:#0006;display:grid;place-items:center;padding:20px;z-index:50}.dialog{width:min(850px,100%);max-height:90vh;overflow:auto;background:#fffdf9;border-radius:14px;padding:18px}.head{display:flex;gap:10px;align-items:center}.head h2{margin-right:auto}.form{display:grid;grid-template-columns:1fr 1fr;gap:10px}.form .wide{grid-column:1/-1}.form label{font-size:12px;font-weight:700;display:grid;gap:5px}.actions{display:flex;justify-content:flex-end;gap:8px;margin-top:14px}.detail dl{display:grid;grid-template-columns:140px 1fr;gap:7px 10px;font-size:13px}.detail dd{margin:0}.count{font-size:12px;color:#777}@media(max-width:650px){.filters,.form{grid-template-columns:1fr}.form .wide{grid-column:auto}}`}</style>
    <div className="bar"><h1>Événements</h1><button className="btn primary" onClick={()=>setShowAdd(true)}>+ Ajouter</button><label className="file">Importer JSON<input type="file" accept=".json,application/json" onChange={importJson}/></label><button className="btn" onClick={()=>downloadJson("evenement-modele.json",jsonTemplate)}>Modèle JSON</button><button className="btn" onClick={()=>downloadJson("evenements-export.json",items)}>Exporter</button></div><div className="msg">{busy?"Enregistrement…":message}</div>
    <section className="filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher événement, conséquence, date…"/><select value={type} onChange={e=>setType(e.target.value)}><option value="">Tous les types</option>{types.map(v=><option key={v}>{v}</option>)}</select><select value={statut} onChange={e=>setStatut(e.target.value)}><option value="">Tous les statuts</option>{statuts.map(v=><option key={v}>{v}</option>)}</select><select value={region} onChange={e=>setRegion(e.target.value)}><option value="">Toutes les régions</option>{regions.map(v=><option key={v.id} value={v.id}>{v.nom}</option>)}</select></section>
    <p className="count">{filtered.length} événement{filtered.length>1?"s":""} sur {items.length}</p><section className="grid">{filtered.map(x=><article className="card" key={x.id}><div className="body"><div className="date">{x.date?.texte||"Date inconnue"}</div><h2>{x.nom}</h2><div className="meta">{x.type} · {x.statut}</div><p className="desc">{x.description}</p></div><button className="more" onClick={()=>setSelected(x)}>Voir la fiche</button></article>)}</section>
    {showAdd&&<div className="back" onMouseDown={e=>{if(e.target===e.currentTarget)setShowAdd(false)}}><section className="dialog"><div className="head"><h2>Ajouter un événement</h2><button className="btn" onClick={()=>setShowAdd(false)}>Fermer</button></div><div className="form">
      <label>Nom<input value={draft.nom} onChange={e=>setDraft({...draft,nom:e.target.value})}/></label><label>Type<input value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})}/></label><label>Début AR<input type="number" value={draft.debut_ar} onChange={e=>setDraft({...draft,debut_ar:e.target.value})}/></label><label>Fin AR<input type="number" value={draft.fin_ar} onChange={e=>setDraft({...draft,fin_ar:e.target.value})}/></label><label>Date affichée<input value={draft.date_texte} onChange={e=>setDraft({...draft,date_texte:e.target.value})} placeholder="4720 AR"/></label><label>Importance<input value={draft.importance} onChange={e=>setDraft({...draft,importance:e.target.value})}/></label>
      <label className="wide">Description<textarea rows={4} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Régions (IDs)<input value={draft.regions} onChange={e=>setDraft({...draft,regions:e.target.value})}/></label><label>Lieux (IDs)<input value={draft.lieux} onChange={e=>setDraft({...draft,lieux:e.target.value})}/></label><label>Factions (IDs)<input value={draft.factions} onChange={e=>setDraft({...draft,factions:e.target.value})}/></label><label>Personnages (IDs)<input value={draft.personnages} onChange={e=>setDraft({...draft,personnages:e.target.value})}/></label><label className="wide">Conséquences (séparées par virgules)<input value={draft.consequences} onChange={e=>setDraft({...draft,consequences:e.target.value})}/></label><label>Tags<input value={draft.tags} onChange={e=>setDraft({...draft,tags:e.target.value})}/></label><label>Statut<input value={draft.statut} onChange={e=>setDraft({...draft,statut:e.target.value})}/></label><label>Source<input value={draft.source} onChange={e=>setDraft({...draft,source:e.target.value})}/></label><label className="wide">Notes<textarea rows={3} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label>
    </div><div className="actions"><button className="btn" onClick={()=>setShowAdd(false)}>Annuler</button><button className="btn primary" onClick={save}>Enregistrer</button></div></section></div>}
    {selected&&<div className="back" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><article className="dialog detail"><div className="head"><h2>{selected.nom}</h2><button className="btn" onClick={()=>setSelected(null)}>Fermer</button></div><p><strong>{selected.date?.texte||"Date inconnue"}</strong> — {selected.description}</p><dl><dt>Type</dt><dd>{selected.type}</dd><dt>Importance</dt><dd>{selected.importance}</dd><dt>Statut</dt><dd>{selected.statut}</dd><dt>Régions</dt><dd>{selected.regions.map(id=>name("regions",id)).join(" · ")||"—"}</dd><dt>Lieux</dt><dd>{selected.lieux.map(id=>name("lieux",id)).join(" · ")||"—"}</dd><dt>Factions</dt><dd>{selected.factions.map(id=>name("factions",id)).join(" · ")||"—"}</dd><dt>Personnages</dt><dd>{selected.personnages.map(id=>name("pnjs",id)).join(" · ")||"—"}</dd><dt>Conséquences</dt><dd>{selected.consequences.join(" · ")||"—"}</dd><dt>Tags</dt><dd>{selected.tags.join(" · ")||"—"}</dd><dt>Source</dt><dd>{selected.source||"—"}</dd><dt>Notes</dt><dd>{selected.notes||"—"}</dd></dl></article></div>}
  </main>
}
