"use client";

import {ChangeEvent,useEffect,useMemo,useState} from "react";
import {regionContains} from "./geography";

type Region={
  id:string;nom:string;type:string;parent_id?:string|null;capitale_lieu_id?:string|null;description:string;histoire?:string;
  gouvernement?:string;culture?:string;religions:string[];factions:string[];personnages_cles:string[];lieux_cles:string[];
  relations:any[];tags:string[];image:string;aliases:string[];statut:string;notes?:string;source?:string;evenements:string[];
};
type RefItem={id:string;nom:string};
type Draft={nom:string;type:string;parent_id:string;capitale_lieu_id:string;description:string;histoire:string;gouvernement:string;
  culture:string;religions:string;factions:string;personnages_cles:string;lieux_cles:string;relations:string;tags:string;image:string;
  aliases:string;statut:string;notes:string;source:string;evenements:string};

const emptyDraft:Draft={nom:"",type:"Nation",parent_id:"",capitale_lieu_id:"",description:"",histoire:"",gouvernement:"",culture:"",
  religions:"",factions:"",personnages_cles:"",lieux_cles:"",relations:"[]",tags:"",image:"",aliases:"",statut:"Actif",notes:"",source:"",evenements:""};
const jsonTemplate:Region={id:"region_exemple",nom:"Région exemple",type:"Nation",parent_id:null,capitale_lieu_id:null,description:"Description courte.",
  histoire:"",gouvernement:"",culture:"",religions:[],factions:[],personnages_cles:[],lieux_cles:[],relations:[],tags:[],image:"",
  aliases:[],statut:"Actif",notes:"",source:"",evenements:[]};
const csv=(v:string)=>[...new Set(v.split(",").map(x=>x.trim()).filter(Boolean))];
const slugId=(v:string)=>"region_"+v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"");
const normalize=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const unique=(v:string[])=>[...new Set(v.filter(Boolean))].sort((a,b)=>a.localeCompare(b,"fr"));
const parseJson=(v:string)=>{try{return v.trim()?JSON.parse(v):[]}catch{return[]}};
function isRegion(v:unknown):v is Region{if(!v||typeof v!=="object")return false;const x=v as Partial<Region>;return typeof x.nom==="string"&&typeof x.description==="string"&&Array.isArray(x.factions)&&Array.isArray(x.tags)&&typeof x.image==="string"}
const downloadJson=(filename:string,data:unknown)=>{const blob=new Blob([JSON.stringify(data,null,2)+"\n"],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url)};

export default function RegionsPage(){
  const [items,setItems]=useState<Region[]>([]),[pnjs,setPnjs]=useState<RefItem[]>([]),[factions,setFactions]=useState<RefItem[]>([]),[lieux,setLieux]=useState<RefItem[]>([]),[events,setEvents]=useState<RefItem[]>([]);
  const [query,setQuery]=useState(""),[type,setType]=useState(""),[statut,setStatut]=useState(""),[parent,setParent]=useState("");
  const [selected,setSelected]=useState<Region|null>(null),[showAdd,setShowAdd]=useState(false),[draft,setDraft]=useState<Draft>(emptyDraft),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const get=async(url:string)=>{try{const r=await fetch(url,{cache:"no-store"});if(!r.ok)return[];const p=await r.json();return Array.isArray(p)?p:p.items??[]}catch{return[]}};
  const load=async()=>{const r=await fetch("/apil7r/pf2-mj/regions",{cache:"no-store"});if(!r.ok)throw new Error("Impossible de charger les régions.");const p=await r.json();setItems(Array.isArray(p)?p:p.items??[]);
    const [a,b,c,d]=await Promise.all([get("/apil7r/pf2-mj/pnj"),get("/apil7r/pf2-mj/factions"),get("/apil7r/pf2-mj/lieux"),get("/apil7r/pf2-mj/evenements")]);setPnjs(a);setFactions(b);setLieux(c);setEvents(d)};
  useEffect(()=>{load().catch(e=>setMessage(e instanceof Error?e.message:String(e)))},[]);
  const maps=useMemo(()=>({regions:new Map(items.map(x=>[x.id,x.nom])),pnjs:new Map(pnjs.map(x=>[x.id,x.nom])),factions:new Map(factions.map(x=>[x.id,x.nom])),lieux:new Map(lieux.map(x=>[x.id,x.nom])),events:new Map(events.map(x=>[x.id,x.nom]))}),[items,pnjs,factions,lieux,events]);
  const name=(k:keyof typeof maps,id?:string|null)=>id?(maps[k].get(id)??id):"—";
  const types=useMemo(()=>unique(items.map(x=>x.type)),[items]),statuts=useMemo(()=>unique(items.map(x=>x.statut)),[items]);
  const filtered=useMemo(()=>{const q=normalize(query.trim());return items.filter(x=>{const h=normalize([x.nom,x.type,x.description,x.histoire,x.gouvernement,x.culture,x.source,...x.tags,...x.aliases].filter(Boolean).join(" "));
    return(!q||h.includes(q))&&(!type||x.type===type)&&(!statut||x.statut===statut)&&(!parent||regionContains(parent,x.id))}).sort((a,b)=>a.nom.localeCompare(b.nom,"fr"))},[items,query,type,statut,parent]);
  const save=async()=>{if(!draft.nom.trim()){setMessage("Le nom est obligatoire.");return}setBusy(true);try{const item:Region={id:slugId(draft.nom),nom:draft.nom.trim(),type:draft.type||"Nation",parent_id:draft.parent_id||null,
    capitale_lieu_id:draft.capitale_lieu_id||null,description:draft.description.trim(),histoire:draft.histoire.trim(),gouvernement:draft.gouvernement.trim(),culture:draft.culture.trim(),religions:csv(draft.religions),factions:csv(draft.factions),
    personnages_cles:csv(draft.personnages_cles),lieux_cles:csv(draft.lieux_cles),relations:parseJson(draft.relations),tags:csv(draft.tags),image:draft.image.trim(),aliases:csv(draft.aliases),statut:draft.statut||"Actif",notes:draft.notes.trim(),source:draft.source.trim(),evenements:csv(draft.evenements)};
    const r=await fetch("/apil7r/pf2-mj/regions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"upsert",item})});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.error||`Erreur HTTP ${r.status}`);setItems(p.items);setDraft(emptyDraft);setShowAdd(false);setSelected(item);setMessage(`${item.nom} enregistrée.`)
  }catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
  const importJson=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value="";if(!file)return;setBusy(true);try{const parsed=JSON.parse(await file.text()),raw=Array.isArray(parsed)?parsed:Array.isArray(parsed?.items)?parsed.items:[parsed];
    const imported:Region[]=raw.map((x:any)=>({...x,id:x.id||slugId(x.nom||""),description:x.description||"",religions:Array.isArray(x.religions)?x.religions:[],factions:Array.isArray(x.factions)?x.factions:[],personnages_cles:Array.isArray(x.personnages_cles)?x.personnages_cles:[],lieux_cles:Array.isArray(x.lieux_cles)?x.lieux_cles:[],relations:Array.isArray(x.relations)?x.relations:[],tags:Array.isArray(x.tags)?x.tags:[],aliases:Array.isArray(x.aliases)?x.aliases:[],evenements:Array.isArray(x.evenements)?x.evenements:[],image:x.image||""}));
    if(imported.some(x=>!isRegion(x)))throw new Error("Le JSON contient au moins une région invalide.");const r=await fetch("/apil7r/pf2-mj/regions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"import",items:imported})});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.error||`Erreur HTTP ${r.status}`);setItems(p.items);setMessage(`${imported.length} région${imported.length>1?"s":""} importée${imported.length>1?"s":""}.`)
  }catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};

  return <main className="rp"><style>{`.rp{max-width:1500px;margin:auto;padding:24px;color:#252a25}.bar{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.bar h1{margin-right:auto}.btn,.file{border:1px solid #c9b98f;background:#fffaf0;color:#6e5319;border-radius:8px;padding:9px 12px;font-weight:700;cursor:pointer}.btn.primary{background:#765719;color:white}.file input{display:none}.msg{min-height:24px;font-size:13px;color:#5d614f}.filters{display:grid;grid-template-columns:2fr repeat(3,1fr);gap:9px;margin:10px 0 18px}.filters input,.filters select,.form input,.form textarea,.form select{width:100%;box-sizing:border-box;border:1px solid #d6cdbd;border-radius:8px;background:#fffdf8;padding:9px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(250px,1fr));gap:14px}.card{border:1px solid #ded7cb;background:#fffdf9;border-radius:12px;overflow:hidden}.body{padding:13px}.card h2{margin:0 0 5px;font-size:17px}.meta{font-size:12px;color:#777}.desc{font-size:13px;line-height:1.45}.more{width:100%;border:0;border-top:1px solid #eee7da;background:#faf7f0;padding:8px;font-weight:700;color:#66542b;cursor:pointer}.back{position:fixed;inset:0;background:#0006;display:grid;place-items:center;padding:20px;z-index:50}.dialog{width:min(850px,100%);max-height:90vh;overflow:auto;background:#fffdf9;border-radius:14px;padding:18px}.head{display:flex;gap:10px;align-items:center}.head h2{margin-right:auto}.form{display:grid;grid-template-columns:1fr 1fr;gap:10px}.form .wide{grid-column:1/-1}.form label{font-size:12px;font-weight:700;display:grid;gap:5px}.actions{display:flex;justify-content:flex-end;gap:8px;margin-top:14px}.detail dl{display:grid;grid-template-columns:140px 1fr;gap:7px 10px;font-size:13px}.detail dd{margin:0}.count{font-size:12px;color:#777}@media(max-width:650px){.filters,.form{grid-template-columns:1fr}.form .wide{grid-column:auto}}`}</style>
    <div className="bar"><h1>Régions & pays</h1><button className="btn primary" onClick={()=>setShowAdd(true)}>+ Ajouter</button><label className="file">Importer JSON<input type="file" accept=".json,application/json" onChange={importJson}/></label><button className="btn" onClick={()=>downloadJson("region-modele.json",jsonTemplate)}>Modèle JSON</button><button className="btn" onClick={()=>downloadJson("regions-export.json",items)}>Exporter</button></div>
    <div className="msg">{busy?"Enregistrement…":message}</div><section className="filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher nom, histoire, gouvernement…"/><select value={type} onChange={e=>setType(e.target.value)}><option value="">Tous les types</option>{types.map(v=><option key={v}>{v}</option>)}</select><select value={statut} onChange={e=>setStatut(e.target.value)}><option value="">Tous les statuts</option>{statuts.map(v=><option key={v}>{v}</option>)}</select><select value={parent} onChange={e=>setParent(e.target.value)}><option value="">Tous les parents</option>{items.map(v=><option key={v.id} value={v.id}>{v.nom}</option>)}</select></section>
    <p className="count">{filtered.length} région{filtered.length>1?"s":""} sur {items.length}</p><section className="grid">{filtered.map(x=><article className="card" key={x.id}><div className="body"><h2>{x.nom}</h2><div className="meta">{x.type} · {x.statut}{x.parent_id?` · ${name("regions",x.parent_id)}`:""}</div><p className="desc">{x.description}</p></div><button className="more" onClick={()=>setSelected(x)}>Voir la fiche</button></article>)}</section>
    {showAdd&&<div className="back" onMouseDown={e=>{if(e.target===e.currentTarget)setShowAdd(false)}}><section className="dialog"><div className="head"><h2>Ajouter une région</h2><button className="btn" onClick={()=>setShowAdd(false)}>Fermer</button></div><div className="form">
      <label>Nom<input value={draft.nom} onChange={e=>setDraft({...draft,nom:e.target.value})}/></label><label>Type<input value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})}/></label>
      <label>Parent<select value={draft.parent_id} onChange={e=>setDraft({...draft,parent_id:e.target.value})}><option value="">Aucun</option>{items.map(v=><option key={v.id} value={v.id}>{v.nom}</option>)}</select></label>
      <label>Capitale (ID lieu)<input value={draft.capitale_lieu_id} onChange={e=>setDraft({...draft,capitale_lieu_id:e.target.value})}/></label><label className="wide">Description<textarea rows={3} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label>
      <label className="wide">Histoire<textarea rows={4} value={draft.histoire} onChange={e=>setDraft({...draft,histoire:e.target.value})}/></label><label>Gouvernement<input value={draft.gouvernement} onChange={e=>setDraft({...draft,gouvernement:e.target.value})}/></label><label>Culture<input value={draft.culture} onChange={e=>setDraft({...draft,culture:e.target.value})}/></label>
      <label>Religions<input value={draft.religions} onChange={e=>setDraft({...draft,religions:e.target.value})}/></label><label>Factions (IDs)<input value={draft.factions} onChange={e=>setDraft({...draft,factions:e.target.value})}/></label><label>PNJ clés (IDs)<input value={draft.personnages_cles} onChange={e=>setDraft({...draft,personnages_cles:e.target.value})}/></label><label>Lieux clés (IDs)<input value={draft.lieux_cles} onChange={e=>setDraft({...draft,lieux_cles:e.target.value})}/></label>
      <label>Tags<input value={draft.tags} onChange={e=>setDraft({...draft,tags:e.target.value})}/></label><label>Alias<input value={draft.aliases} onChange={e=>setDraft({...draft,aliases:e.target.value})}/></label><label>Statut<input value={draft.statut} onChange={e=>setDraft({...draft,statut:e.target.value})}/></label><label>Événements (IDs)<input value={draft.evenements} onChange={e=>setDraft({...draft,evenements:e.target.value})}/></label>
      <label className="wide">Relations (JSON)<textarea rows={3} value={draft.relations} onChange={e=>setDraft({...draft,relations:e.target.value})}/></label><label>Image<input value={draft.image} onChange={e=>setDraft({...draft,image:e.target.value})}/></label><label>Source<input value={draft.source} onChange={e=>setDraft({...draft,source:e.target.value})}/></label><label className="wide">Notes<textarea rows={3} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label>
    </div><div className="actions"><button className="btn" onClick={()=>setShowAdd(false)}>Annuler</button><button className="btn primary" onClick={save}>Enregistrer</button></div></section></div>}
    {selected&&<div className="back" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><article className="dialog detail"><div className="head"><h2>{selected.nom}</h2><button className="btn" onClick={()=>setSelected(null)}>Fermer</button></div><p>{selected.description}</p><dl>
      <dt>Type</dt><dd>{selected.type}</dd><dt>Parent</dt><dd>{name("regions",selected.parent_id)}</dd><dt>Capitale</dt><dd>{name("lieux",selected.capitale_lieu_id)}</dd><dt>Gouvernement</dt><dd>{selected.gouvernement||"—"}</dd><dt>Culture</dt><dd>{selected.culture||"—"}</dd><dt>Histoire</dt><dd>{selected.histoire||"—"}</dd>
      <dt>Religions</dt><dd>{selected.religions.join(" · ")||"—"}</dd><dt>Factions</dt><dd>{selected.factions.map(id=>name("factions",id)).join(" · ")||"—"}</dd><dt>PNJ clés</dt><dd>{selected.personnages_cles.map(id=>name("pnjs",id)).join(" · ")||"—"}</dd><dt>Lieux clés</dt><dd>{selected.lieux_cles.map(id=>name("lieux",id)).join(" · ")||"—"}</dd><dt>Événements</dt><dd>{selected.evenements.map(id=>name("events",id)).join(" · ")||"—"}</dd><dt>Tags</dt><dd>{selected.tags.join(" · ")||"—"}</dd><dt>Source</dt><dd>{selected.source||"—"}</dd><dt>Notes</dt><dd>{selected.notes||"—"}</dd>
    </dl></article></div>}
  </main>
}
