export enum SkillCategory {
  STATS = 'STATS',
  MAGIE = 'MAGIE',
  CORROMPUS = 'CORROMPUS', // TODO DELETE
  PAROLIERS = 'PAROLIERS',
  SPIRITES = 'SPIRITES',
  ARCANES = 'ARCANES',
  SOLDATS = 'SOLDATS',
  ROYALS = 'ROYALS', // TODO DELETE
  PACIFICATEURS = 'PACIFICATEURS'
}
