FROM node:22-bookworm-slim AS build

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build:web:misc

FROM nginx:1.27-alpine
COPY support/pf2-synology/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/apps/web-misc /usr/share/nginx/html
EXPOSE 80
