FROM node:22-bookworm-slim AS build

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npx nx build api-jdr
RUN npm prune --omit=dev

FROM node:22-bookworm-slim

WORKDIR /app
ENV NODE_ENV=production
ENV PF2_DATA_ROOT=/app/seed
COPY --from=build /app/dist/api-jdr ./dist/api-jdr
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/apps/web-misc/src/pf2-mj/data ./seed

EXPOSE 3333
CMD ["node", "dist/api-jdr/main.js"]
